### ISSUE TITLE
Second half of the animation is not rendered

### ISSUE THREAD

**Issue by zhengs** [airbnb/lottie-web#1006]
**Tell us about your environment**
mac OS

* **Browser and Browser Version:**
* **After Effects Version:**
After Effects CC 15.0

**What did you do? Please explain the steps you took before you encountered the problem.**
Load the template (attached). Use bodymovin to export the "video" comp.
**What did you expect to happen?**
Expected to see the 6s animation look identical to AE.

**What actually happened? Please include as much _relevant_ detail as possible.**
The whole animation contains two swipe effects. The 1st starts around 1s into the animation, the 2nd starts around 3.5s. However, the animation exported from Bodymovin seems to only have the 1st swipe. The 2nd swipe seems gone.

**Please provide a download link to the After Effects file that demonstrates the problem.**

[lines-loop3-no-effects.aep.zip](https://github.com/airbnb/lottie-web/files/1969066/lines-loop3-no-effects.aep.zip)

**Comment by bodymovin** [comment]
Hi, you have two consecutive Alpha Layers "first saturation 2" and "1.91:1 image"
That is making the exporter ignore one of them because in AE that setting doesn't do anything.
I'll see if I can fix it on the next deploy, but meanwhile, if you change your last layer Track Matte to none, it should work fine.
