### ISSUE TITLE
Missing character from exported character list

### ISSUE THREAD

**Issue by igor-nikolic** [airbnb/lottie-web#1024]
Hi,
I'm having a problem with changing characters on an animation. How can I export all characters so I can't get this error (Missing character from exported character list)? Any hints or printscreens of the solution?

Thanks in advance

**Comment by bodymovin** [comment]
Hi, you can add a hidden text layer with all characters you want supported.
Or you can unselect Glyphs from the AE bodymovin panel and use real text providing the font externally.

**Comment by kimown** [comment]
@bodymovin 

I unselect Glyphs in AE bodymovin panel , and export the json file, so no chars in data.json, but then console throw errors：

![image](https://user-images.githubusercontent.com/7932380/44645924-febd9680-aa0b-11e8-9bc6-b26a2d9b0ec4.png)
![image](https://user-images.githubusercontent.com/7932380/44646006-3c222400-aa0c-11e8-82c1-c0edb52cddfb.png)

Seems we must have `chars` property in json file.

**Comment by bodymovin** [comment]
@kimown the canvas renderer only supports glyphs, you should use svg if you want to use fonts?

**Comment by kimown** [comment]
@bodymovin 

I see, Thanks for your reply, I have another question: how can AE do this if text from user input.

https://github.com/airbnb/lottie-web/issues/1024#issuecomment-388986859

> Hi, you can add a hidden text layer with all characters you want supported.

I thought it's impossible, because a complete font contains too many too many characters, sorry for my poor knowledge of AE, I really don't know how to do this.
