### ISSUE TITLE
Lottie causing problems with Google Translate

### ISSUE THREAD

**Issue by ghost** [airbnb/lottie-web#1134]
**Tell us about your environment**
Mac 2015 Retina Display

**Browser and Browser Version:**
Chrome v.67

**Problem**
My animations were working great on the website! I decided to add Google Translate and ended up getting hundreds of errors every second. I discovered by deduction that this was because of my Lottie animations. My HTML looks like this for the animation: 

`<div id="choosing" class="cardAnim"></div>` 

and the js : 

`  var animation2 = bodymovin.loadAnimation({
    container: document.getElementById('choosing'),
    renderer: 'svg',
    loop: true,
    autoplay: true,
    path: '/img/choosing/data.json',
    assetsPath: ''
  })` .

Anyways, the error Google translate is giving me from Lottie is : 

`element_main.js:405 Uncaught TypeError: a[b].target.className.indexOf is not a function
   at au.v.Ai (element_main.js:405)`

Thanks in advance!

**Comment by bodymovin** [comment]
Hi, I'm not sure how this is related to lottie itself. It looks like that library is trying to access a property of an element that doesn't have it.
Can you share a link where it fails?

**Comment by AntonOta** [comment]
Hey @bodymovin, any updates on the situation?

**Comment by bodymovin** [comment]
It seems to be related to this similar case:
https://github.com/hjalmers/angular-bootgrid/issues/1
I would check if there is a way to avoid parsing certain elements or I would post it on their side.
Also, is there a continuous mode? Perhaps turning it off there won't be so many errors at least.

**Comment by AntonOta** [comment]
For now, what I did was I paused all animations on the website when I detected Google Translate and replayed when Google Translate was not active. Was the best solution I could find...

**Comment by mrharel** [comment]
We had the same issue, i wrote in details about it here: https://medium.com/@amir.harel/a-b-target-classname-indexof-is-not-a-function-at-least-not-mine-8e52f7be64ca

**Comment by bodymovin** [comment]
@mrharel thanks for the post, it looks like it's exactly the same. Do you have inline svg elements in your view?

**Comment by mrharel** [comment]
yes we do.

**Comment by bodymovin** [comment]
those are probably the DOM elements that don't have the "indexOf" function and break with Google Translate

**Comment by c78867886** [comment]
@mrharel  I saw how you deal with this bug. May I know where you catch the error?
Can you provide some example code for this? Thank you!

**Comment by rooheengarg** [comment]
@mrharel Thanks for the blog. Can you please share how have you fixed this issue? 
Uncaught TypeError: a[b].target.className.indexOf is not a function I am getting the same error but not because of Google Translate Extension but its because of some other extension. 
It would be a great help if someone can help me out

**Comment by zaycker** [comment]
An issue continues to live. It is almost 2020 :)
The cause is the "Google Website Translator" embedded into Chrome now (not as an extension as it was earlier). When you try to open any non-native language page in Chrome it's "Translator" starts to parse nodes on the page and checks it's className in a straight way:
```
if (a[b].target && a[b].target.className && (0 <= a[b].target.className.indexOf(bc) ...
```

it checks only the existence of className and executes indexOf right after it. But for `SVGElement` className is an instance of `SVGAnimatedString` which doesn't have `#indexOf()`.

I tried `meta[name="google"][content="notranlate"]`, I tried `class="notranslate"`. Often it doesn't help. Especially with lazy-loaded SVGs (we have react + lottie + lazy loaded svg-jsons).

I tried to declare `SVGAnimatedString.prototype.indexOf` at the top of the page. But seems like Translator works in its own sandbox...

We were forced to switch off Sentry error tracker cause of the frequency of this error and exceeding our budget without profit. Especially when there is animation and exceptions are generated infinitely.

Some of the stackoverflow answers tell "turn off translator inside browser properties". Aha. Inside the client's browser. Give me just a sec...

Researching solution.

**Comment by eriktoyra** [comment]
@zaycker I'm having the exact same issue with my React app which lazy loads content with SVGs. I'm also using Sentry but I'm able to ignore those errors by using the "Ignore -> For... -> Custom" menu in the event details page in the Sentry UI. 

You should also be able to ignore the errors by filtering the events with the `beforeSend` callback in the `Sentry.init(...)` config. See https://docs.sentry.io/error-reporting/configuration/filtering/?platform=browser

As for how to prevent the actual error from happening, I'm still clueless as I have found nothing that actually prevents it from happening.

**Comment by m-v-novikov** [comment]
Also, you can ignore this by setting `ignoreErrors` property on initialization. I saw they recommended that In some issue years ago)))
https://docs.sentry.io/clients/javascript/config
```
{
  ignoreErrors: [/^Exact Match Message$/] // can be an array of strings, but RegExp preffered
}
```
