### ISSUE TITLE
 How to play animation and music at the same time

### ISSUE THREAD

**Issue by AhnHarry** [airbnb/lottie-web#1136]
Good morning

Is there a way to get the music together when the animation is loaded?

I use it well
Thank you.

**Comment by bodymovin** [comment]
Hi, Lottie doesn't handle audio and video layers.
But you can use a custom audio player and control the animation position related to your audio layer using js.

**Comment by kudanai** [comment]
It's been a while since this issue was filed so I'm closing it.

Please refer to the following for lottie+audio features

[https://github.com/airbnb/lottie-web/wiki/Audio](https://github.com/airbnb/lottie-web/wiki/Audio)
[https://lottiefiles.github.io/lottie-docs/advanced_interactions/#level-8-sound-effects](https://lottiefiles.github.io/lottie-docs/advanced_interactions/#level-8-sound-effects)
