### ISSUE TITLE
dna.json draws incorrectly at ToT, is fine at 5.2.1

### ISSUE THREAD

**Issue by kjlubick** [airbnb/lottie-web#1228]
**Tell us about your environment**

* **Browser and Browser Version:** Chrome 68 and Firefox 52.8.1
* **After Effects Version:** Unknown

**What did you do? Please explain the steps you took before you encountered the problem.**
Compare the first frame of the given lottie file when rendered with:
[5.2.1](https://jsfiddle.net/35bhq2k8/)
and at [ToT](https://jsfiddle.net/fo2d10hw/1) (specifically [1b0a2852](https://github.com/airbnb/lottie-web/commit/1b0a285228407ba83669c59ed95054a149aae019))

**What did you expect to happen?**
I expect them to be rendered the same.
**What actually happened? Please include as much _relevant_ detail as possible.**

The dots are at the wrong place at ToT.  It looks ok when animated, but at specifically the first frame, it's off.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.lottiefiles.com/946-dna  I didn't make this, just noticed the behavior difference.

**Comment by bodymovin** [comment]
Issue fixed in version 5.3.0
This issue revealed a larger problem regarding precomputing properties so they would be available for expressions.
Since on some expressions, the order they are computed matters, precalculating position ended up rendering the frame incorrectly.
To fix this, I've had to add a new conversion to expressions during export, to set all accesses to transform properties as members of a custom transform object.
Thanks for reporting!
