### ISSUE TITLE
Flickering Animations - Translate3d? 

### ISSUE THREAD

**Issue by joyannahirst** [airbnb/lottie-web#1328]
Hello! I think I am having trouble with the transform: translate3d(0,0,0). 

The animation has large lines running through it that disappear at different device sizes. I have tried everything I could think of to fix it:  flexbox, absolute positioning, margin 0 auto... I have toggled all of these. 

The only thing that seems to help is to toggle off the translate3d. The designer is using the latest AE CC 2018  and body movin 5.2.1. 

[https://www.dropbox.com/s/u9une0fw9d33c0r/Screenshot%202018-10-25%2014.37.19.png?dl=0](screenshot)

[https://accessventures.org/our-approach/investment-approach/](Example)

**Comment by bodymovin** [comment]
Hi, does that screenshot have missing lines?
Can you help me identify which ones are missing?
Regarding translate3d, since that property promotes layers to the GPU there might be some artifacts if the size is significantly reduced or pixels are not rounded.
But I can't see clearly what lines are disappearing to have a better understanding of what might be going on.

**Comment by bodymovin** [comment]
@joyannahirst if you can share the json or aep I can take a better look.
But I guess the problem is with masked strokes on browsers.
If I am right, you need to add a transparent rectangle (ie: Group with nested Rectangle Shape and Fill at 0% opacity) below those strokes that cover the whole surface of the shape including the stroke width. You should do this on every layer that has strokes and is masked.
That will probably fix it.

**Comment by joyannahirst** [comment]
Ok! I'm meeting with the designer now. We will try that first, If that doesn't work I'll see if I can send you the json file.

**Comment by joyannahirst** [comment]
@bodymovin Here is the file! [https://www.dropbox.com/s/t0endpsp9bqwf8m/data.json?dl=0](url)

**Comment by joyannahirst** [comment]
It's happening in Chrome and Also in Safari.

**Comment by andre94** [comment]
Hi guys, I’m experiencing the same only in iphone safari. See andreabalbo.com to test it. I also use the translate3d with velocity.js. If i remove it, the animation isn’t flickering. Thanks

**Comment by joyannahirst** [comment]
Sure! Here you go. [https://www.dropbox.com/home/Pyxl%20Shared%20Files/clients/access%20ventures/animations/working%20files/AV_Master%20Animation%20One%20Pocket/AV_One%20Pocket%20165x165%20folder](url)

**Comment by bodymovin** [comment]
@joyannahirst I can't access that link, can you email me the project?

**Comment by bodymovin** [comment]
@andre94 your issue seems to be different, but I don't know what it is related to.
Is there any reason why  you're overriding the transform style of the svg?
Can you apply that scale to the containing div?

**Comment by joyannahirst** [comment]
@bodymovin Thank you so much! It's fixed. I really appreciate your dedication to help us figure this out.
