### ISSUE TITLE
Question: Is there an alternative to animate in 2s / skip frames / posterize for Bodymovin?

### ISSUE THREAD

**Issue by nickmadedesign** [airbnb/lottie-web#1337]
Hello!

My goal is to animate in 24fps but have certain objects play at 12fps (animated in 2s). I could use Posterize or Precomp and use Preserve framerate for nested comps, but neither of those seems to be supported based on the Wiki and my renders.

Does anyone have a workaround for this that plays nice with Bodymovin?

This is under AE CC 2019, Bodymovin 5.4.1.

Thanks!
Nick

**Comment by nickmadedesign** [comment]
Using posterizeTime as an expression and converting to keyframes is one option but perhaps someone knows of another wizardry.

**Comment by nickmadedesign** [comment]
@bodymovin Is it possible to adjust the framerate to use a 12fps comp framerate with the Bodymovin output at 24fps playback (effectively doubling the frames)?

**Comment by bodymovin** [comment]
Hi, I need to think about this one.  
Right now you can roll your own player so you can control the framerate at your pace.  
But posterizing precomps is not supported for now.

**Comment by nickmadedesign** [comment]
Hi!
By roll my own player, what do you mean?
Out of curiosity, what is the player's default FPS? 30?

**Comment by bodymovin** [comment]
I mean you can control the playhead of the animation by calling `anim.goToAndStop(frame)` on a loop that you control yourself instead of relying on the native ticker.
Regarding the refreshing interval, the player relies on the browser's refreshing capabilities that are exposed via `requestAnimationFrame`, which is usually 60 times per second.
You can call `anim.setSubframe(false)` to have it respect the original refreshing interval.  
In both cases, the amount of rendered frames is always the one defined in AE, but by default the player will try to interpolate between subframes to get a smoother effect.

**Comment by nickmadedesign** [comment]
Aha, I had `anim.setSubframe(false)` written incorrectly because I misread the Usage section. It works fine now. Thanks, Hernan!
