### ISSUE TITLE
Too many images after exporting

### ISSUE THREAD

**Issue by ahmadqwer** [airbnb/lottie-web#1399]
Hello,

I am working on a project that have too many animations using the Bodymovin.
the issue is that when i export one animation on After Effect i see a json file and assets images , a lot of images(38 image). I understand that these images are the animation layers.
my question is can i make all these images into one image that include all of these images, because i have a lot of these animations, and my browser is lagging because it should load all of these images at once.

can you please help me.

Thanks.

**Comment by bodymovin** [comment]
Hi, ideally you should try using shape layers instead of rasterized ones. Do you know why they are exported as images? are they illustrator layers?

If they need to be images because they can't be converted to shape layers, you can select on the settings of the composition in AE to export the images as part of the json file.
