### ISSUE TITLE
Problem with export files 

### ISSUE THREAD

**Issue by WojBar** [airbnb/lottie-web#1400]
Hi
Im trying to put some json files onto my website, but it doesnt work at all.
I wonder is this file ok, or maybe it exceed some limitations of AE to json conversion?
Thats the json file: [ar.zip](https://github.com/airbnb/lottie-web/files/2629407/ar.zip)

**Comment by WojBar** [comment]
And that's AE 2019 file 
[ar_icon.zip](https://github.com/airbnb/lottie-web/files/2629778/ar_icon.zip)

**Comment by bodymovin** [comment]
Hi, I couldn't open the project because of an AE 2019 bug.
But apparently there is an expression that is looking for a specific layer in a comp:
`comp('00.CONTROL').layer('CONTROL').effect('BGColor')('Color')`
If that composition is not part of the render tree, you should add it on the settings as an extra composition.
