### ISSUE TITLE
Lottie with particle effect?

### ISSUE THREAD

**Issue by JerryKuK** [airbnb/lottie-web#1410]
Hi, 
I know lottie doesn't support particle effects, but I saw [this](https://www.lottiefiles.com/1643-exploding-star) on LottieFiles.
It looks like he used particle effects.
How can I make the similar effect and export the json which works fine?

AE CC 2015
bodymovin 5.4.2

**Comment by Danjuanlab** [comment]
It is just path/mask animation.There are many paths, but because they are regular circles,so there are not many anchor points.
But if you want to try irregular shapes, or much more particle effects than in this case, you can try to simulate the operation. First, use the particle plug-in to simulate the effect you want, then use Auto-trace to track all paths to generate mask animation, and then adjust the color.
