### ISSUE TITLE
Rendered Json is just white or blank

### ISSUE THREAD

**Issue by SakulleugiM** [airbnb/lottie-web#1420]
Hi,

I am pretty new to bodymovin but super excited at its potential. I have been trying to implement an animation to a website but I think I might be doing something wrong.

I have created the after effect file and rendered it out using bodymovin, everything went well so far. However when implementing the json file, apparently its empty, nothing happens.

I am a designer and not so well versed on a coding side of things but the person in charge of dev says nothing happens when implemented.

So it might be that my animation uses effects that are not supported, or I am missing something.

But the fact that it renders without errors, means I am a bit lost to what might be the issue.

I would be grateful if I could get some assistance. Still getting the hang of it.

Project files:
[Monty Github.zip](https://github.com/airbnb/lottie-web/files/2671649/Monty.Github.zip)

Many thanks
Sakul

**Comment by Danjuanlab** [comment]
My AE2018 can't open your AE file. But according to the content of the json file, I guess you were used the built-in plugins so that it doesn't work. Because bodymovin doesn't support all AE functions, especially the most of the built-in effects are not supported. If the corresponding built-in effects are applied in the project, then the json file will be exported and the browser will be blank. Check [here](https://github.com/airbnb/lottie-web/wiki) to know more details.
