### ISSUE TITLE
Upload a G-Zipped Animation to Adwords

### ISSUE THREAD

**Issue by Interacy** [airbnb/lottie-web#1441]
Is it possible to upload a g-zipped animation to google adwords?

If its possible how does it work?

**Comment by bodymovin** [comment]
I'm not exactly sure how adwords works, but for ads usually you just need to upload a regular zip with all the assets.
They take care of gzipping them when serving.

**Comment by bodymovin** [comment]
you shouldn't need to add a gzip to a zip file.
ad servers usually take care of serving files gzipped, they just want to whole bundle, when zipped, to be under 150kb.
In order to save some kb, you can take a look at some other builds [here](https://github.com/airbnb/lottie-web/tree/master/build/player) that reduce filesize by reducing features.
