### ISSUE TITLE
Text / number replacement.

### ISSUE THREAD

**Issue by ryantheleach** [airbnb/lottie-web#1461]
Can an easier API be added for text / variable / number replacement be added to lottie?

It would be awesome to be able to create animations from live data for twitch streaming graphics.

**Comment by bodymovin** [comment]
Any suggestions?

**Comment by Danjuanlab** [comment]
Hey, I am also using bodymovin to create streaming animations, and I am working hard to make SVG animations change with the gift data.

Currently I can use the jquery to location the class name then replace the image in the animation , which is very convenient.
However, for the update of text, the current update method needs to know the index value of the text in order to accurately locate the text layer. This method is not universal, because the index of the text layer may not be able to be in the same in different animation of the same designer. It will be adjusted according to the animation.Last week, I also e-mail to Hernan about this things, he told me that I can do it by writing lottie-api myself.But it will take me some time to understand the full API.

At present, my scheme is to try the class name instead of the index value of the text layer. When updating, it traverses the entire animation layer and updates the text of the layer of the target class name. Such traversal will take longer to complete. Also, if you have multiple sub-animation comps in a json file, then such traversal will update the text data of all sub-animations, but in fact we only play these One of the animations. So I am currently considering how to optimize performance.
