### ISSUE TITLE
Explain different libs?

### ISSUE THREAD

**Issue by badtant** [airbnb/lottie-web#1503]
Hi,

I'm trying to understand the different libs there is. I want to only render svg (no canvas) in a webpage.
So what are then the differences between these options:

lottie_html 491 kb
lottie_light_html 401 kb
lottie_light 360 kb
lottie_svg 450 kb

**Comment by bodymovin** [comment]
lottie_html: html renderer with all html features
lottie_light_html  html renderer without expressions
lottie_light svg renderer without expressions and effects
lottie_svg svg renderer with all features
Unless you're minifyinf later, always try to use the .min.js versions of each one.
And make sure you serve them gzipped

**Comment by badtant** [comment]
thanks!
so lottie_light should be renamed to lottie_light_svg?

Is this the feature list i should be looking at and should the "light" libs be included there also?
http://airbnb.io/lottie/supported-features.html

I'm still not exactly sure I understand the difference between the svg and html libs. When i tried the html one it did render svg?

**Comment by bodymovin** [comment]
yes, lottie_light is lottie_light_svg, but since it was originally the only light version I'll keep it with that name.

The html renderer is a hybrid of svgs and divs.
It relies on divs to apply 3d transforms but still each layer is an svg element.
If you're not applying 3d transforms, the html renderer can sometimes have better performance than the svg renderer because of how browsers treat textures uploaded to the gpu.
It depends on the animation.
