### ISSUE TITLE
PlaySegments one after another

### ISSUE THREAD

**Issue by allanjsx** [airbnb/lottie-web#1527]
**What did you do? Please explain the steps you took before you encountered the problem.**
When user pushes a button, I expect to run segment A once, and after A complete, loop segment B.

Here's my code:
      
```
var animation = bodymovin.loadAnimation({
    container: document.getElementById('lottie-demo'),
    renderer: 'svg',
    loop: true,
    autoplay: true,
    path: 'animation.json'
 })

function onButtonClick() {
    animation.playSegments([AStart, AEnd], true) 
    animation.playSegments([BStart, BEnd], false) 
}
```
      
**What did you expect to happen?**
According to the documentation, when button click, segment A should immediately start and run once, and B should start to loop after A complete its first cycle (because the second param is false)

**What actually happened? Please include as much _relevant_ detail as possible.**

I cannot visually see A runs at all and B start to playing after pushing button.

**Comment by mrmos** [comment]
I can confirm that I'm seeing a similar issue. 

Basically, I'm trying to do

```javascript
animation.playSegment([BStart, BEnd], false)
```

My animation is jumping immediately to the first frame of `BStart` without waiting for the current segment to complete.

Digging into the code, it appears that the the issue is occurring in the `AnimationItem.prototype.adjustSegment` method.

This is the method:

```
AnimationItem.prototype.adjustSegment = function(arr, offset){
    this.playCount = 0;
    if(arr[1] < arr[0]){
        if(this.frameModifier > 0){
            if(this.playSpeed < 0){
                this.setSpeed(-this.playSpeed);
            } else {
                this.setDirection(-1);
            }
        }
        this.timeCompleted = this.totalFrames = arr[0] - arr[1];
        this.firstFrame = arr[1];
        this.setCurrentRawFrameValue(this.totalFrames - 0.001 - offset);
    } else if(arr[1] > arr[0]){
        if(this.frameModifier < 0){
            if(this.playSpeed < 0){
                this.setSpeed(-this.playSpeed);
            } else {
                this.setDirection(1);
            }
        }
        this.timeCompleted = this.totalFrames = arr[1] - arr[0];
        this.firstFrame = arr[0];
        this.setCurrentRawFrameValue(0.001 + offset);
    }
    this.trigger('segmentStart');
};
```

It seems that no matter what you pass in for `forceFlag` the code will set the `firstFrame` and call `setCurrentRawFrameValue`, forcing the animation to the next segment without waiting for the previous segment to finish. 

I can create an isolated test case if necessary.

**Comment by mrmos** [comment]
If I revert back to version 5.3.1, before this commit (https://github.com/airbnb/lottie-web/commit/5b28a2190267e5b3c81c1df1e8fb93ac3d257c98#diff-672d74ac11c82f81d30a7c78239824a9) the `forceFlag` works as expected
