### ISSUE TITLE
Issues with playSegments running a single time

### ISSUE THREAD

**Issue by zkingdesign** [airbnb/lottie-web#1555]
**Tell us about your environment**
Mac OS 
Lottie 5.5 (latest version)

* **Browser and Browser Version:**
Chrome 73
* **After Effects Version:**
 CC 16.0.1 (Build 48)

**What did you do? Please explain the steps you took before you encountered the problem.**
So what I'm trying to do is to play an animation on wheel event, but I'm having a really hard time because if playSegments forceflag is set to true the wheel event triggers multiple times.

Another thing I noticed is that setting my #lottie div to opacity 0 it plays ok.

Here the animation is set to opacity: 0.001 in css https://www.useloom.com/share/a2638da859764b81ab206108dfbed6b5
Here the animation is set to opacity : 0 and this is how it should work
https://www.useloom.com/share/627162c7604f424c825e03733717c0d1

You can clearly see the issue on the left hand side with the text animation.

Also created a reduced test case of jsfiddle:
https://jsfiddle.net/7xvy26cg/

Any help is greatly appreciated.

**Comment by bodymovin** [comment]
Hi, not sure I understand the issue but it seems to go beyond the scope of the library.
forceflag shouldn't be affecting the number of wheel events that are triggered. Perhaps you should consider throttling that event since it is usually triggered more than once.
I suggest that you build a simple version to try to figure out what exactly is going on, or perhaps you can get help on stackoverflow.
