### ISSUE TITLE
Alpha inverted matte doesn't work properly

### ISSUE THREAD

**Issue by henriqrossatto** [airbnb/lottie-web#1632]
* **Chrome
* **After Effects Version: 16.0

I'm working with Alpha Inverted Matte in a simple animation for IOs. Inside the preview, the animation work properly but when the client test in code the file doesn't read the Alpha Inverted Matte

How the animation should work https://lottiefiles.com/share/eLe0Jq

Print of my client attached
![IMG_5469](https://user-images.githubusercontent.com/30601233/58096568-bfdbfc00-7bab-11e9-96df-a34deec087e3.jpg)

*I'm using the last version of lottie

**Comment by bodymovin** [comment]
Hi, can you post this issue in the ios repo? They'll be more helpful than me in this matter.
https://github.com/airbnb/lottie-ios

**Comment by henriqrossatto** [comment]
Hi, thanks for the feedback. I found the problem. Was the version that dev was using to implement the animation. Alpha Inverted Matte is available in 3.0 and dev was using 2.5 or something like that.

**Comment by surmvoise** [comment]
I use an Alpha Inverted Track Matte in my AE comp but in the svg animation in the browser the track matte is not inverted. How can I get this to work?

I use this library: https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.5.9/lottie.min.js

**Comment by bodymovin** [comment]
@surmvoise hi, can you share the .aep?

**Comment by surmvoise** [comment]
Hi, thanks for the reply. Here you go:
[Inverted Track Matte.aep.zip](https://github.com/airbnb/lottie-web/files/3701382/Inverted.Track.Matte.aep.zip)

**Comment by bodymovin** [comment]
@surmvoise I just tried it and it seems to be working. The only browsers that doesn't support inverted track mattes are Edge and IE.
Can you share a link with your implementation?

**Comment by bodymovin** [comment]
Track matte masks are not very performant on Safari. Any type of masks that are not clip paths struggle in large sizes

**Comment by surmvoise** [comment]
Do you mean CSS clip paths? What kind of masks do I have to use in after effects in order to be converted as clip pathS by bodymovin?

**Comment by ision-industries** [comment]
@bodymovin sorry I am way late to this thread but you mentioned "any type of masks that are not clip paths struggle in larger sizes". I have two problems regarding this:

1. What are clip paths?
2. How do the masks "struggle" in larger sizes? I have a problem with alpha inverted track mattes having a feathered or blurry border. Could that be because I have the animation displaying at 256x256 resolution?

**Comment by ision-industries** [comment]
@bodymovin sorry I am way late to this thread but you mentioned "any type of masks that are not clip paths struggle in larger sizes". I have two problems regarding this:

1. What are clip paths?
2. How do the masks "struggle" in larger sizes? I have a problem with alpha inverted track mattes having a feathered or blurry border. Could that be because I have the animation displaying at 256x256 resolution?

**Comment by ision-industries** [comment]
@bodymovin sorry I am way late to this thread but you mentioned "any type of masks that are not clip paths struggle in larger sizes". I have two problems regarding this:

1. What are clip paths?
2. How do the masks "struggle" in larger sizes? I have a problem with alpha inverted track mattes having a feathered or blurry border. Could that be because I have the animation displaying at 256x256 resolution?

**Comment by ision-industries** [comment]
@bodymovin sorry I am way late to this thread but you mentioned "any type of masks that are not clip paths struggle in larger sizes". I have two problems regarding this:

1. What are clip paths?
2. How do the masks "struggle" in larger sizes? I have a problem with alpha inverted track mattes having a feathered or blurry border. Could that be because I have the animation displaying at 256x256 resolution?

**Comment by ision-industries** [comment]
@bodymovin sorry I am way late to this thread but you mentioned "any type of masks that are not clip paths struggle in larger sizes". I have two problems regarding this:

1. What are clip paths?
2. How do the masks "struggle" in larger sizes? I have a problem with alpha inverted track mattes having a feathered or blurry border. Could that be because I have the animation displaying at 256x256 resolution?

**Comment by ision-industries** [comment]
@bodymovin sorry I am way late to this thread but you mentioned "any type of masks that are not clip paths struggle in larger sizes". I have two problems regarding this:

1. What are clip paths?
2. How do the masks "struggle" in larger sizes? I have a problem with alpha inverted track mattes having a feathered or blurry border. Could that be because I have the animation displaying at 256x256 resolution?

**Comment by ision-industries** [comment]
@bodymovin sorry I am way late to this thread but you mentioned "any type of masks that are not clip paths struggle in larger sizes". I have two problems regarding this:

1. What are clip paths?
2. How do the masks "struggle" in larger sizes? I have a problem with alpha inverted track mattes having a feathered or blurry border. Could that be because I have the animation displaying at 256x256 resolution?

**Comment by ision-industries** [comment]
@bodymovin sorry I am way late to this thread but you mentioned "any type of masks that are not clip paths struggle in larger sizes". I have two problems regarding this:

1. What are clip paths?
2. How do the masks "struggle" in larger sizes? I have a problem with alpha inverted track mattes having a feathered or blurry border. Could that be because I have the animation displaying at 256x256 resolution?

**Comment by ision-industries** [comment]
@bodymovin sorry I am way late to this thread but you mentioned "any type of masks that are not clip paths struggle in larger sizes". I have two problems regarding this:

1. What are clip paths?
2. How do the masks "struggle" in larger sizes? I have a problem with alpha inverted track mattes having a feathered or blurry border. Could that be because I have the animation displaying at 256x256 resolution?

**Comment by ision-industries** [comment]
@bodymovin sorry I am way late to this thread but you mentioned "any type of masks that are not clip paths struggle in larger sizes". I have two problems regarding this:

1. What are clip paths?
2. How do the masks "struggle" in larger sizes? I have a problem with alpha inverted track mattes having a feathered or blurry border. Could that be because I have the animation displaying at 256x256 resolution?

**Comment by ision-industries** [comment]
@bodymovin sorry I am way late to this thread but you mentioned "any type of masks that are not clip paths struggle in larger sizes". I have two problems regarding this:

1. What are clip paths?
2. How do the masks "struggle" in larger sizes? I have a problem with alpha inverted track mattes having a feathered or blurry border. Could that be because I have the animation displaying at 256x256 resolution?

**Comment by ision-industries** [comment]
@bodymovin sorry I am way late to this thread but you mentioned "any type of masks that are not clip paths struggle in larger sizes". I have two problems regarding this:

1. What are clip paths?
2. How do the masks "struggle" in larger sizes? I have a problem with alpha inverted track mattes having a feathered or blurry border. Could that be because I have the animation displaying at 256x256 resolution?

**Comment by ision-industries** [comment]
@bodymovin sorry I am way late to this thread but you mentioned "any type of masks that are not clip paths struggle in larger sizes". I have two problems regarding this:

1. What are clip paths?
2. How do the masks "struggle" in larger sizes? I have a problem with alpha inverted track mattes having a feathered or blurry border. Could that be because I have the animation displaying at 256x256 resolution?

**Comment by ision-industries** [comment]
@bodymovin sorry I am way late to this thread but you mentioned "any type of masks that are not clip paths struggle in larger sizes". I have two problems regarding this:

1. What are clip paths?
2. How do the masks "struggle" in larger sizes? I have a problem with alpha inverted track mattes having a feathered or blurry border. Could that be because I have the animation displaying at 256x256 resolution?

**Comment by henriqrossatto** [comment]
@ision-industries can you share your file or some previews? So we can check how we can help you with this error.

**Comment by ision-industries** [comment]
@henriqrossatto here is the private file link to the animation. 
[](https://assets3.lottiefiles.com/private_files/lf30_7mo1As.json)

Note: if you preview the animation on the Lottiefiles iOS App then you will see the alpha inverted matte problem. You can see the edges of the matte are blurry and feathered in this screenshot ![image](https://user-images.githubusercontent.com/58711145/93007988-7603eb80-f53d-11ea-88c1-040e53fe83a1.jpeg)

This screenshot is from my iPad, since it's displayed at a larger size could that be the issue causing the blurry edges? @bodymovin did mention alpha inverted track mattes struggle displayed at larger sizes. 

Here is another screenshot from the google chrome browser on my iPad. I don't notice any blurry or feathered edges, although I can't play the animation full screen, it's cut off. ![image](https://user-images.githubusercontent.com/58711145/93008040-2a9e0d00-f53e-11ea-8f95-faa32b2b018d.jpeg)

Here is a screenshot from previewing the animation on lottiefiles on Android. The alpha inverted matte appears to be functioning fine. ![image](https://user-images.githubusercontent.com/58711145/93008470-08f35480-f543-11ea-9704-e2032a85f1c4.png)

**Comment by henriqrossatto** [comment]
Looks that in iOS system the animation is inverted. Could you share the AE file?

**Comment by ision-industries** [comment]
@henriqrossatto the position is supposed to be animated. Here is the AE project file, I should have linked it last night. Sorry


[Alpha Inverted Matte Lottie Project.aep.zip](https://github.com/airbnb/lottie-web/files/5214927/Alpha.Inverted.Matte.Lottie.Project.aep.zip)

**Comment by henriqrossatto** [comment]
Test this one https://lottiefiles.com/share/FAMPmN

**Comment by ision-industries** [comment]
@henriqrossatto Thanks for sending this over. I tested your link in the Lottiefiles App and it still displays the "blurry" edges of the matte layers. You can see in this screenshot
![image](https://user-images.githubusercontent.com/58711145/93041025-6ce84c80-f619-11ea-93da-bf768db6a2c5.jpeg)

But when I click on the link and open it in a mobile browser it displays perfect as it should. Here's a screenshot ![image](https://user-images.githubusercontent.com/58711145/93041074-999c6400-f619-11ea-8c3d-60a2413009b4.jpeg)

It's really weird, and alpha inverted mattes are supported on iOS. So since it only has a problem on the lottiefiles app but plays everywhere else fine, should I be concerned still? I've been trying to figure this problem out for a few months now. Since the animation only has a problem on the iOS app, does that mean it will be problematic on other apps for iOS if a developer uses the animation in their app?

**Comment by henriqrossatto** [comment]
I understand, yes maybe can be a lottiefiles bug. I believe the better way will be testing it inside the code.

**Comment by ision-industries** [comment]
Is there a way I can test the animations code? I'm an animator not a developer lol.

**Comment by henriqrossatto** [comment]
Justing code I believe. I'm a motion designer too =/.

Any ideas @bodymovin?

**Comment by ision-industries** [comment]
Okay so there are a few other apps that can test Lottie animations on iOS. I downloaded the app called Lottie Samples for the iPad and tested the animation on there. Here is a screenshot of the animation in the Lottie Samples app. ![image](https://user-images.githubusercontent.com/58711145/93275122-0b93bb00-f78a-11ea-8a18-4dcc71f91f98.jpeg)

The animation plays correctly and there is no issue with the alpha inverted matte. Even though the animation has that feathering artifact in the LottieFiles app it says there are "0" warnings. So I'm guessing the LottieFiles app has a bug.
