### ISSUE TITLE
Lottie + Joysticks n Sliders animationData static

### ISSUE THREAD

**Issue by MariuszDabrowski** [airbnb/lottie-web#1674]
Environment
- After Effects CC (15.0.0)
- Bodymovin' 5.5.5
- Chrome 75.0.3770.90

Take a look at `index.html`, in there I have copied over the [interactive joystick'n sliders](https://codepen.io/airnan/pen/EmdXGo) example. However, when I try to manipulate the `s and e` values, they don't reflect in the animation.

I also noticed that when an animation is running the `s and e` values don't reflect what the animation is doing, they remain static.

I assume this is something to do with the way my after effects file is setup. Is there something special that needs to be done in the `.ae` file to allow manipulation or the `animationData` object?

Project files - [project.zip](https://github.com/airbnb/lottie-web/files/3291772/project.zip)

Thanks!

**Comment by Inventsable** [comment]
Hi, you're missing the [lottie-api](https://github.com/bodymovin/lottie-api) library. I'm not sure how that codepen example is set up to actively change properties as they exist in After Effects within `lottie.animationData` because typically I've found that changing lottie's underlying values don't reliably have any affect.

I have a [simple example with an HTML joystick here](https://www.willthis.work/), and [the code for this is available here](https://github.com/Inventsable/Vue-Lottie-JoysticksNSliders/blob/master/main.js#L181). Using the lottie-api isn't much harder than registering a function similar to that one on `DOMLoaded`

**Comment by MariuszDabrowski** [comment]
@Inventsable ahhh that's it! Haven't messed about with Bodymovin' since the switch over to Lottie.

Thank you for the help and the awesome example code :)

**Comment by iamsibtehassan** [comment]
Hey Mariusz,
Can you please also share the updated project file? 
Thanks
