### ISSUE TITLE
Shapes broken in Bodymovin

### ISSUE THREAD

**Issue by sunknudsen** [airbnb/lottie-web#1676]
**Tell us about your environment**

macOS Mojave 10.14.5

* **Browser and Browser Version:**

Firefox 67.0.2 (64-bit)

* **After Effects Version:**

16.1.1 (Build 4)

**What did you do? Please explain the steps you took before you encountered the problem.**

- Installed Bodymovin via https://www.adobeexchange.com/creativecloud.details.12557.html (also tried from GitHub repo at https://github.com/airbnb/lottie-web/tree/master/build/extension)

- Opened stock animation `teamwork_13.aep` in After Effects

- Selected `teamwork_13` in Bodymovin, selected `Desktop` as destination

- Pressed Render (using `Demo` setting)

- Realized shapes are broken opening `demo.html` in Firefox

- Looked at preview in Bodymovin, same issue

**What did you expect to happen?**

I expected the demo would look the same as exporting to video

**What actually happened? Please include as much _relevant_ detail as possible.**

What it should look like:

<img width="903" alt="Screen Shot 2019-06-15 at 8 53 49 AM" src="https://user-images.githubusercontent.com/2117655/59551746-61a4fd80-8f4c-11e9-8815-c99c2ab64eb2.png">

What it looks like in preview:

<img width="640" alt="Screen Shot 2019-06-15 at 9 08 21 AM" src="https://user-images.githubusercontent.com/2117655/59551819-2e16a300-8f4d-11e9-9e1d-e89777b96d18.png">

Probably a newbie config error but can’t figure it out after spending half an hour searching the web. Hope someone can help.

**Please provide a download link to the After Effects file that demonstrates the problem.**

https://sunknudsen.com/teamwork_13.aep

**Comment by Inventsable** [comment]
Hello, great art, and good news! It is indeed a very simple config error. Make sure sure that "Hidden" and "Guides" included in your config:

<img width="456" alt="ice_screenshot_20190615-073932" src="https://user-images.githubusercontent.com/37279677/59552854-e0943900-8f40-11e9-834d-1fd00429f077.png">

Which produces the correct positioning for limbs:

<img width="456" alt="ice_screenshot_20190615-073923" src="https://user-images.githubusercontent.com/37279677/59552872-13d6c800-8f41-11e9-88ca-2edffea878a9.png">

As a general rule of thumb, I've noticed that whenever I have layers/shapes unexpectedly going to the top left of the screen, it's because I'm missing a layer in my parenting chain so it's position defaults at [0,0]. In this instance, the BaseHose of a Rubberhose arm (the actual stroke) is trying to find two guide layers (Wrists and Shoulders) and use their positioning as a reference -- but unless the config includes Guided layers, the Basehose doesn't find any layer to correctly reference and defaults to [0,0] (which is the exact top-left corner of the animation).

**Comment by sunknudsen** [comment]
Amazing, thanks so much @Inventsable!

**Comment by Inventsable** [comment]
No problem! Art looks great by the way.

**Comment by sunknudsen** [comment]
Shout-out to [Pijus](https://www.behance.net/pijusgraphics) for the artworks. 🙌

**Comment by d-korolkov** [comment]
> Hello, great art, and good news! It is indeed a very simple config error. Make sure that "Hidden" and "Guides" are enabled in your config:


Oh gush! Thanks a lot!
