### ISSUE TITLE
Masks on a 3D layer not working correctly

### ISSUE THREAD

**Issue by IndifferentPoets** [airbnb/lottie-web#1761]
Hi, I'm getting an issue where a 3D layer with a mask is cutting off weirdly. I've tried to do all the research I can, but can't seem to put my finger on the exact issue.

This is what it should look like:
![590x160](https://user-images.githubusercontent.com/53916954/62732459-addc5d80-ba24-11e9-9267-3df612205fac.gif)

This is what it is doing:
https://lottiefiles.com/share/8Eq5AC

I've attached the AE file for reference, you can ignore any "Missing files" messages.
https://drive.google.com/file/d/157LSjfhgOxk7GDORTIbtHDqNLrUhOlVs/view?usp=sharing

Let me know if you have any ideas!

Thanks

**Comment by Danjuanlab** [comment]
It is not recommended to use a 3D layer with a mask, which will have some unexpected results. Generally speaking, the SVG renderer can achieve better compatibility than the HTML renderer. 
Personally, animations like this are best made using path animation, because such compatibility is better, the computational pressure is smaller, and the file size of the animation is well controlled.

**Comment by kudanai** [comment]
Hello. I'm closing this issue as it's been stale for some time. If this problem persists in a more recent version, please re-open it or file a new issue.
