### ISSUE TITLE
Error handling in loadAnimation.

### ISSUE THREAD

**Issue by gujral1997** [airbnb/lottie-web#1768]
Hi @bodymovin. How can we handle the error thrown by `loadAnimation` method? 
Thanks in advance!

**Comment by bodymovin** [comment]
Hi, what error in particular are you referring to?

**Comment by gujral1997** [comment]
Like, I want to log the error when invalid JSON gets loaded.

**Comment by anhtaiH** [comment]
Hi! I also mentioned this in slack, but related to this issue it would be nice to have a way to gracefully handle exceptions, especially if it is because the JSON contains an unsupported feature. I created a codesandbox with some JSON data that's causing the exception (one or two of which you mentioned is a bug), and the other one is due to an unsupported feature. I'll update this codesandbox with more examples as I come across more problem JSON files.

https://codesandbox.io/s/gifted-frog-oizfk

Also, thanks for your hard work Hernan! Really appreciate all of the work you've done for the community.

**Comment by escakot** [comment]
> Hi! I also mentioned this in slack, but related to this issue it would be nice to have a way to gracefully handle exceptions, especially if it is because the JSON contains an unsupported feature. I created a codesandbox with some JSON data that's causing the exception (one or two of which you mentioned is a bug), and the other one is due to an unsupported feature. I'll update this codesandbox with more examples as I come across more problem JSON files.
> 
> https://codesandbox.io/s/gifted-frog-oizfk
> 
> Also, thanks for your hard work Hernan! Really appreciate all of the work you've done for the community.

Thanks for the codesandbox. It allowed me to test a few things.
Try catch seems to work for loadAnimation() when setting animationData.
However, if you're using path in loadAnimation, try catch doesn't work.
`
lottie.loadAnimation({
  container: document.getElementById("container"),
  renderer: "svg",
  loop: true,
  path: "https://github.com/invalid.json",
  autoplay: true
});
`

The console prints:
`XMLHttpRequest cannot load https://github.com/invalid.json due to access control checks.`
or
`
Failed to load resource: the server responded with a status 404 ()
Error: Invalid value for <svg> attribute width="undefined"
Error: Invalid value for <svg> attribute height="undefined"
Error: Invalid value for <rect> attribute width="undefined"
Error: Invalid value for <rect> attribute height="undefined"
`

**Comment by bodymovin** [comment]
Hi, error handling has been added on version 5.6.2

**Comment by maynarddemmon** [comment]
And the documentation for this error handling can be found where?
