### ISSUE TITLE
Text Replacement inside code instead use a png

### ISSUE THREAD

**Issue by henriqrossatto** [airbnb/lottie-web#1829]
More a doubt than a problem. Inside some projects I see the necessity from devs to change the text inside the animation. Actually I'm using a image to allow them replace any text they need.

I would like to know if have any way to export the animation file with a text layer/text box and the dev change or adapt the text inside the code and make it in some way interactive instead use a image to replace that.

Thank you.
Henrique

**Comment by Danjuanlab** [comment]
The method of modifying the text content in an animation requires different interaction methods in different situations. First of all, when the modified text layer does not add the text Animate or other parts of the animation have nothing to do with it, the modified method is the same as the image modification URL, we only need to give the text layer a canonical name. In this way, the front-end program can change the content of the text layer through JS. The reference code is as follows:

 `  $(‘.FeedBackMark text tspan').html(‘Egglet Live Lab Test Text’);`
        When an animation is added to the text in the animation, or other elements are associated with the expression in the text layer, then you need to use lottie_api to complete the modification, so that the animation works properly. For example, the text follows the mask path to make up and down movements. This animation actually renders each character independently in the webpage, so a simple JS can't change the content, and let the new text animation work normally. The reason is that the previous method only modifies the loaded content in the webpage, while using lottie_api is to modify the animation content and recalculate the rendering. The reference code is as follows:

```
Var animapi=lottie_api.createAnimationApi(anim);//anim is the default animation program name
Var animkp=animapi.getKeyPath(‘.FeedBackMark’’);
animkp.getElements()[0].setText(‘This is new text content’, 0);
```

**Comment by henriqrossatto** [comment]
@Danjuanlab thanks for it
