### ISSUE TITLE
Now, apart from the English operating system, is the problem of exporting all colors invalid?

### ISSUE THREAD

**Issue by wyfang** [airbnb/lottie-web#1874]
Now, apart from the English operating system, is the problem of exporting all colors invalid?

And I haven't used this tool for a long time, because after all the updates, the colors are all turned black and white. I learned that because the operating system is not English, my working environment is difficult to be an English operating system, so is this problem still there?

**Comment by wyfang** [comment]
<img width="1029" alt="截屏2019-11-20下午3 44 53" src="https://user-images.githubusercontent.com/17900420/69218948-c542ef00-0bac-11ea-9cc1-a0013011a069.png">
OK, I still can't test it. it's a pity

**Comment by Danjuanlab** [comment]
This problem is not a bug with the program of the plugin itself, but a problem with AE, because the different encoding methods will make the plugin not return the correct result when performing the steps in AE, which must be solved by ADOBE. In addition,such as the gradual change caused by the non-English environment cannot be exported normally.
