### ISSUE TITLE
Autoplay false is being ignored

### ISSUE THREAD

**Issue by tone4407** [airbnb/lottie-web#1901]
* **Browser and Browser Version:**
Chrome 78
* **After Effects Version:**
17

```
var animation = bodymovin.loadAnimation({
  container: document.getElementById('bm'),
  renderer: 'svg',
  loop: false,
  autoplay: false,
  path: 'https://cdn2.hubspot.net/hubfs/279033/Website_Template_Files/Marco_2019/Marco-Animated-Circles-Icons-2.json'
})
```

Autoplay false seems to be ignored with 5.5.9. It was working as expected with version 5.4.2.

For reference, I have autoplay set to false because I'm manually triggering the animation like so:

```
animation.addEventListener('DOMLoaded',function(e){
  animation.playSegments([0,69], false);
});
```

**Comment by bodymovin** [comment]
hi, can you share a link with a simple implementation?
I see it working fine on my end

**Comment by tone4407** [comment]
Thanks, hernan. Here's a pen: https://codepen.io/tone4407/pen/gObrQR

As you'll notice, the animation plays from start to finish on load, then stops. From there I can use the Back/Next links to playSegments. I'd like for the animation not to autoplay.

The only thing I've changed was the version form 5.4.2 to 5.5.9.

**Comment by bodymovin** [comment]
Hi, there is a behavior attached to the DOMLoaded event that starting triggering the animation once it loads on line 24.
````js
animation.addEventListener('DOMLoaded',function(e){
  animation.playSegments([0,69], false);
});
````

**Comment by tone4407** [comment]
Thank you. You're correct, but isn't it only supposed to play segments 0-69? On page load, it plays the whole animation.

I guess I'm just a little confused as to why this worked in v5.4.2, but it no longer works in v5.5.9. I updated my pen to v5.4.2 and it works properly.

**Comment by bodymovin** [comment]
by passing false as the second argument, it's probably trying to render a first full play loop before playing the segment.
Can you try passing the second argument as `true` to `playSegments`?
I see your point that it worked differently in v5.4.2 but I would not be sure what is the expected behavior in this scenario.
On one side autoplay is set to `false`, but on the other side, by passing `false` as the second argument to `playSegments`, implicitly it's requesting the player to do a full loop before setting the new segment.

**Comment by tone4407** [comment]
Sure enough. That did the trick. Thank you very much!
