### ISSUE TITLE
High CPU usage (above 50%)

### ISSUE THREAD

**Issue by outwork** [airbnb/lottie-web#1941]
**Tell us about your environment**
Wordpress CMS

* **Browser and Browser Version:**
Really high on Chrome and high on Firefox

**What did you do? Please explain the steps you took before you encountered the problem.**
I am working on my portfolio website right now (http://pixelbeast.hu/) and experiencing issues with  high CPU usage (really high on Chrome and high on Firefox). The forrest scene in the background is pretty complex and the CPU usage gets above 50%. This is a bug or is it normal?

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://we.tl/t-KrZ5S72TLx

**Comment by bodymovin** [comment]
Hi, there are several things you can try to improve performance:
for you background animation you might want to set `anim.setSubframe(false)` so it doesn't render subframe values. It will only render rounded frame values which should reduce significantly the amount of ticks to render.
Also, try the canvas renderer, it might be more performant in this case.
And finally, the `eye2` and `eye1` animations have the masks opacity animated. This forces the svg renderer to use mask tags instead of clip-paths which have a big performance hit. Try animating the layer opacity instead of the mask itself.

**Comment by outwork** [comment]
Thank you for your help!

Probably this is a dumb question but how can i add `anim.setSubframe(false)` to the js file?
This is the content of the js file:

lottie.loadAnimation({
  container: document.getElementById('section-9-59'), // the dom element that will contain the animation
  renderer: 'svg',
  loop: true,
  autoplay: true,
  path: 'wp-content/uploads/2020/01/forrest.json' // the path to the animation json
});

Thanks!

**Comment by MehdiRaash** [comment]
dear @bodymovin, _"A general question"_: Shouldn't the resource usage reduces when exporting  **Canvas** instead of SVG?

**Comment by bodymovin** [comment]
@MehdiRaash it depends on features, but yes, as a general rule, it should reduce resource usage indeed
