### ISSUE TITLE
Bodymovin and Masks

### ISSUE THREAD

**Issue by iurichiba** [airbnb/lottie-web#1995]
Hi,

I'm trying to learn a bit about After Effects, so I made a _new_ animation.
However, I can't figure out how to use masks so that Bodymovin understands it correctly to export it. It works well enough on After Effects itself and on the Bodymovin preview, but the mask doesn't seem to work on `lottie-ios`: https://gfycat.com/uncomfortableevilfireant (After Effects on the left, iOS simulator on the right)

Through my searches, I found a lot of questions about bodymovin and masks, but there were a lot of different approaches, even workarounds. I guess it would be nice to have a set of **dos and don'ts** about Bodymovin and Masks. Any tips?

You can download my project here: https://we.tl/t-DQEcGUHNU2

Thanks in advance :)

**Comment by Danjuanlab** [comment]
No mask is used in your animation, but your animation can feel the strokes are clipped during playback. This is because the realization principle of stroke animation in SVG animation has a boundary, and this boundary will only be flush with the path. Since only the center stroke is currently supported, half of the strokes may appear to be isolated. Out of bounds. At the same time, because this boundary will always be slower when following the path animation, you will also see this isolation phenomenon when the animation changes faster.

As a solution, draw a rectangle larger than the original shape in the stroke layer and change its transparency to 0%. This way the default visual boundary will always be larger than the path of your target graphic.
[favorite-animation-fixed.zip](https://github.com/airbnb/lottie-web/files/4215255/favorite-animation-fixed.zip)

**Comment by iurichiba** [comment]
@Danjuanlab I didn't get it, sorry, can you explain it again? Also, the fixed version didn't work, I still get the same result after exporting (a full black square when I wanted a heart-shaped layer).

The problem I'm having is on the **Heart Fill** layer, it has a mask that links to the **Heart Outline** path (maybe that's the problem?).

I'm attaching a screenshot of the layers, that could help a bit:
![Screen Shot 2020-02-17 at 14 33 23](https://user-images.githubusercontent.com/2319719/74675548-8cf28300-5192-11ea-8d08-79118ad33e38.png)

**Comment by bodymovin** [comment]
Hi, lottie-ios and lottie-android don't support expressions.
Can you try removing them and see if it works?

**Comment by Danjuanlab** [comment]
> @Danjuanlab I didn't get it, sorry, can you explain it again? Also, the fixed version didn't work, I still get the same result after exporting (a full black square when I wanted a heart-shaped layer).
> 
> The problem I'm having is on the **Heart Fill** layer, it has a mask that links to the **Heart Outline** path (maybe that's the problem?).
> 
> I'm attaching a screenshot of the layers, that could help a bit:
> ![Screen Shot 2020-02-17 at 14 33 23](https://user-images.githubusercontent.com/2319719/74675548-8cf28300-5192-11ea-8d08-79118ad33e38.png)

You just need to duplicate the heart stroke layer, change this layer to fill, and remove the stroke. Then place it on top of the fill layer and use an alpha mask so that IOS can support it.
[favorite-animation fix2.zip](https://github.com/airbnb/lottie-web/files/4217269/favorite-animation.fix2.zip)

**Comment by iurichiba** [comment]
> Hi, lottie-ios and lottie-android don't support expressions.
> Can you try removing them and see if it works?

Hi!

I removed the expressions and replicated any animations with those properties and it worked fine.
It wasn't a problem with the mask after all, hahaha!

Thank you very much :)
