### ISSUE TITLE
Error: bodymovin is not defined

### ISSUE THREAD

**Issue by LauraV6** [airbnb/lottie-web#1998]
I've made an animation in After Effects and converted it to HTML with Bodymovin.

![image](https://user-images.githubusercontent.com/44572461/74850011-b568b180-5339-11ea-8521-05c3b248d173.png)
My file includes style.css, index.html, script.js, lottie.js and data.json

I received the error 'bodymovin is not defined'
How can I fix this?

```
<div id="bm"></div>
<script src="script.js"></script>
<script src="lottie.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.5.0/lottie_html.js"></script>

var animation = bodymovin.loadAnimation({
  container: document.getElementById('bm'),
  renderer: 'svg',
  loop: true,
  autoplay: true,
  path: 'data.json'
})

**Comment by bodymovin** [comment]
hi, can you share a link with the implementation?

**Comment by LauraV6** [comment]
https://laurav6.github.io/Endsend/

**Comment by LauraV6** [comment]
https://laurav6.github.io/Endsend/

**Comment by bodymovin** [comment]
you need to change the order of your script tags. Since you are loading first the `script.js` and then `lottie.js`, lottie is not ready when `script.js` executes.
As a side note, you are loading the lottie library twice.
If you are using the cdnjs version, use the .min version with is much lighter, and remove the local version:
`https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.6.4/lottie_svg.min.js`

**Comment by LauraV6** [comment]
Thank you, it's working :)
