### ISSUE TITLE
occasionally there is a state that all Lottie animations never play

### ISSUE THREAD

**Issue by ape-casear** [airbnb/lottie-web#2011]
**Tell us about your environment**
version: 5.5.9

* **Browser and Browser Version:**
electron: 5.0.11

* **After Effects Version:**
Don't know

**What did you do? Please explain the steps you took before you encountered the problem.**
My app has many Lottie animations to play. for example, someone enters the room or someone sends a gift to another.  sometimes there are multi animations play at the same time. 
the problem is some users report that the animation is stuck. I find that all instances generated by function 'loadAnimation'  will never play, and I saw the hook of 'data_ready' is working. but the animation was not playing as respect.

**What did you expect to happen?**
animation plays

**What actually happened? Please include as much _relevant_ detail as possible.**
the animation is stuck. all instances generated by function 'loadAnimation'  will never play, and I saw the hook of 'data_ready' is working.

**Please provide a download link to the After Effects file that demonstrates the problem.**
: <

**Comment by Danjuanlab** [comment]
当前端存在多动画并发的时候，前端需要按照业务需要自己构建动画信息池来作为缓冲，不然就会出现你所说的多动画并发情况。其次安卓和苹果在lottie支持的功能上就不同，如果动画显示不一或者动画卡住请检查一下单独测试是否能顺利播放动画，其次动画的制作复杂度也会引发一些性能上的卡顿。另外使用loadAnimation生成的实例如果前端动画没有成功加载，那么请再根据案例调试一下代码；如果加载出来了，但是一次都不会播放或者是就只会播放一次，请尝试使用goToAndPlay(value, isFrame)函数播放。

When there is multi-animation concurrency on the front end, the front-end needs to build an animation information pool as a buffer according to business needs, otherwise you will have the situation of multi-animation concurrency. 

Secondly, Android and iOS are different in the features that lottie supports. If the animation is not the same or the animation is stuck, please check whether the animation can be played successfully.
 
Thirdly, the complexity of animation production will also cause some performance freezes. In addition, if the instance generated by loadAnimation is not successfully loaded, then please debug the code according to the case; if it is loaded, but it will not play once or will only play once, please try to use goToAndPlay(value, isFrame) function to play the animation.

**Comment by ape-casear** [comment]
@Danjuanlab  你好，我这那些lottie的图片什么的都是下载本地保存，再播放的。 所有的动画也都播放过正常的， 目前遇到的情况就是使用者反应偶尔的动画卡住了， 因为那块动画是js的animate动画+lottie，我看日志就卡在了lottie loadAnimation之后，监听data_ready也执行了，但是就是不播放，特点还有 1. 所有的动画都不会播放了 2.除非重启程序，不然永远不会回复正常 。  我目前知道的能出现这种情况办法就是把electron程序最小化，或者息屏，lottie的动画就会卡在data_ready之后，不会播放，待你重新打开屏幕，focus到程序上他才会开始播放，但是用户是正常使用的时候卡住的，所以应该不是这种原因导致的

**Comment by Danjuanlab** [comment]
> @Danjuanlab 你好，我这那些lottie的图片什么的都是下载本地保存，再播放的。 所有的动画也都播放过正常的， 目前遇到的情况就是使用者反应偶尔的动画卡住了， 因为那块动画是js的animate动画+lottie，我看日志就卡在了lottie loadAnimation之后，监听data_ready也执行了，但是就是不播放，特点还有 1. 所有的动画都不会播放了 2.除非重启程序，不然永远不会回复正常 。 我目前知道的能出现这种情况办法就是把electron程序最小化，或者息屏，lottie的动画就会卡在data_ready之后，不会播放，待你重新打开屏幕，focus到程序上他才会开始播放，但是用户是正常使用的时候卡住的，所以应该不是这种原因导致的

可以上传一个例子来看看。听你的描述，问题似乎是浏览器中JS判断你当前网页未处于激活状态，所以不会渲染动画。

**Comment by ape-casear** [comment]
@Danjuanlab   我使用的是vue-electron这个脚手架搭建的electron项目，大部分的lottie动画播放都是如下面例子
```
this.animate = lottie.loadAnimation({
    container: document.querySelector(`.flow-box`),
    renderer: 'svg', // canvas svg  html
    loop: false,
    autoplay: false,
    path: jsonFilePath // 相对位置的json文件路径
})

this.animate.addEventListener('data_ready', () => {
    myApp.log.info('** 礼物流光 data_ready ** ')
    this.animate.play()
})

this.animate.addEventListener('complete', () => {
    myApp.log.info('** 礼物流光 compelete ** flow_id:')
    this.animate.destroy()
    this.animate = ''
    // 播放结束  do something else
})
this.animate.onError = function(errorType, nativeError, errorProps) {
    myApp.log.info(`[channel-valud-gift_playFlow] onError ${errorType} ${nativeError} ${errorProps}`)
   // 这个函数看日志就没见他触发过
}
```
然后在组件的destroyed声明周期函数里有对this.animate的判断
```
if (this.animate) {
        this.animate.onError = null
        this.animate.destroy()
        this.animate = null
}
```

我自己一直没复现出用户反馈的情况

**Comment by Danjuanlab** [comment]
首先尝试不要destory动画，测试一下。其次可以试试goToAndPlay来播放动画。我的理解，在程序再加的时候就通过loadAnimation加载完所有的动画，需要的时候再播放。如果每次播放完就destory，那你下次播放的时候还要再请求，在一段时间使用中，其实这样更消耗网络资源。

**Comment by ape-casear** [comment]
@Danjuanlab  全部load不太现实，动画太多了，还是动态的，遇到一个下载一个，然后播放，第二次播放同样的动画不会再去下载的。  2 不destroy的话，多个实例能挂载在同一个`container: document.querySelector(`.flow-box`),`上吗？ 而且destroy不是释放了资源了吗？ 3 goToAndPlay看到他里面也就是
```
this.goToAndStop(value, isFrame, name);
this.play();
```
加了个goToAndStop， 我也复现不了问题，改了play => goToAndPlay也不知道有没有解决问题 😂

**Comment by Danjuanlab** [comment]
play和gotoandplay不同的地方在于，一个动画如果已经成功播放过一次后，它的播放游标（方便理解）就停在最后一帧，如果此时你的loop：false时，你再使用play（）是无法播放的。因为游标不会自动回到0帧。而gotoandplay则可以让游标回到0再播放。

加载方法是自己业务程序策略问题，我个人觉得遇到再加载不好。不摧毁动画的话，多个实例不能加到同一容器。

**Comment by ape-casear** [comment]
@Danjuanlab  我把this.animate.play()改成this.animate.goToAndPlay(0)后😂，动画直接不播放了
而且动画都不显示出来的。 看他svg里面的g标签都是style="display:none"的。而且可以多个动画挂载同一个dom节点上的，多个同时显示，起码renderer: 'svg'是这样的

**Comment by bodymovin** [comment]
Hi, is the issue solved?

**Comment by ape-casear** [comment]
maybe this problem is triggered due to the error which executed at 'animation.goAndPlay(0)' and the animation had been destroyed
