### ISSUE TITLE
[BUG] Drop shadow has been clipped since update

### ISSUE THREAD

**Issue by tacocat1000** [airbnb/lottie-web#2062]
Hello,

when I uploaded my Lottie file last year everything was fine. But recently I noticed that the drop shadow has changed. Now the shadow is clipped  even though I didn't changed it.
It's implemented with the Lottie player. How can I fix this?
Thank you!

<img width="184" alt="Screenshot 2020-03-25 at 16 07 05" src="https://user-images.githubusercontent.com/62658552/77551648-e7c67b00-6eb2-11ea-9cd6-c614017e3979.png">

**Comment by bodymovin** [comment]
Hi, I changed the way drop shadows work on the latest player because of performance issues and render issues on large resolution devices.
Now you need to specify explicitly the size of the filter to guarantee the drop shadow exceeds the bounding box of the affected element on the rendererSettings
https://github.com/airbnb/lottie-web/wiki/Renderer-Settings#filtersize-svg-renderer

**Comment by tacocat1000** [comment]
Hi, thank you so much for your reply! 
Is there any possibility to specify the filter size inside the Lottie web player? https://lottiefiles.com/web-player

**Comment by bodymovin** [comment]
@tacocat1000 not sure, can you ask the lottiefiles team about that?
