### ISSUE TITLE
Color render issue

### ISSUE THREAD

**Issue by bchu777** [airbnb/lottie-web#2078]
Hi!
I am new to After effects and the bodymovin extension both of which I have been able to download.
The issue that I am having is when I render the animation, it only renders in this one bright red color. Everything else works perfectly, but for some reason I can't seem to get the correct colors to render.
Also as a side note, I downloaded the animation from a template and the composition that I want to render is called "Title_10_render". Ultimately my goal is to just have a nice pre-loader title animation. Any tips on doing that if the file doesn't work with bodymovin?

I attached a link to the google drive AEP:
https://drive.google.com/open?id=190lseKPLR0LNRJf2s9IpFYZ_rLRbUcFs

Thank you in advance.

**Comment by bodymovin** [comment]
Hi, there are two issues on this project.
First, you need to add the Color composition as an extra Comp since it's used on expressions and is not part of the render tree. Make sure you delete all precomps from that comp since precomps in external comps are not supported.
the other is that you are using a fill effect on strokes, which doesn't work well on svgs. I'd suggest that you use the stroke color itself instead.

**Comment by bchu777** [comment]
Hi!
Thank you for the explanation.
I was able to switch the color issue to strokes easily.
I ran into two issues:
-I can't delete the pre-comps without the final composition getting messed
up
-I don't know how to add the color comp as an extra comp

Thank you again,
Brandon C

**Comment by bodymovin** [comment]
I tried removing the pre comps from the Color comp and every seemed fine. What do you mean by messed up?
On the bodymovin panel, on the settings of the comp, there is an option that says Extra Comps. You should select Color from there.
