### ISSUE TITLE
Bodymovin doesn't render

### ISSUE THREAD

**Issue by OlifemB** [airbnb/lottie-web#2343]
Hi. Bodymovin doesn't start rendering. When i press "Render", it do this and nothing more
![image](https://user-images.githubusercontent.com/32907240/97208083-cc667a00-17cb-11eb-8d2a-15080106ccfb.png)

Preview look like this
![image](https://user-images.githubusercontent.com/32907240/97208758-89f16d00-17cc-11eb-8432-61de47f2a7ee.png)

Whats happened? ((

After Effects 2020 17.0.0
Bodymovin 5.7.3
Scripts allowed.

**Comment by bodymovin** [comment]
hi, does it happen with any composition?

**Comment by OlifemB** [comment]
Yes, in all.  I even reinstalled the after effects, but the problem remained.
Half a year ago I successfully used it, but now it doesn't work ((
I think it can't connect to my composition, because in preview only 1 frame or 0 in other.
May be bodymovin has debugger, error log or some where i can see execution status?

**Comment by OlifemB** [comment]
![wtf](https://user-images.githubusercontent.com/32907240/97411304-1f961500-1911-11eb-8348-980ee781bc04.png)

**Comment by bodymovin** [comment]
Preview is showing a single frame because you probably haven't selected an animation to preview yet.
Regarding why the animation doesn't start rendering, I don't know. I haven't seen this behavior before.
It looks like the extension is not being able to send messages to the CEP panel. Do you have any other extensions installed?

**Comment by OlifemB** [comment]
Ok. I'm reinstalled that holey Windows and plugin has been starting. Thank ^^
