### ISSUE TITLE
unexpected file(troy) in lottie-web@5.7.4

### ISSUE THREAD

**Issue by zhaoxingyue** [airbnb/lottie-web#2373]
Hi all, This issue is not a bug.

I use `npm install lottie-web --save`, But i got a unexpected file(troy) in lottie-web, this file looks not useful for this package. Can anyone please delete this file?

- lottie-web@5.7.4

![image](https://user-images.githubusercontent.com/15117664/100347491-6cf4c780-3020-11eb-8f3d-7b5b39a20271.png)

**Comment by bodymovin** [comment]
hi, that file is not part of the bundle. Could it be something generated by a local script on your device?

**Comment by zhaoxingyue** [comment]
> hi, that file is not part of the bundle. Could it be something generated by a local script on your device?

Yes i know that file is not part of the bundle.

This is the steps when i encountered the problem:

- step1

```
$ yarn add lottie-web@5.7.4
```
or 
```
$ npm install lottie-web@5.7.4 --save
```

- step2

```
$ ls node_modules/lottie-web/
```

You will find that file in the bundle.

![image](https://user-images.githubusercontent.com/15117664/100608902-1b15af80-3348-11eb-892c-81526af918cd.png)

**Comment by supoo** [comment]
I also have this issue using the exact same method as @zhaoxingyue.
<img width="89" alt="2020-12-04-15-25-19" src="https://user-images.githubusercontent.com/1104023/101224950-00438380-3645-11eb-9ae3-5e12799f5aa6.png">

This caused us a lot of issues because our pipeline stopped working all of a sudden and we had to go through every new package before finding this file. The error was our zip utility expecting file names to be ASCII.

**Comment by bodymovin** [comment]
done, it'll be fixed on the next deploy
