### ISSUE TITLE
increased memory after remove animations

### ISSUE THREAD

**Issue by alexaaaant** [airbnb/lottie-web#2437]
**Tell us about your environment**
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
* **Browser and Browser Version:**
Google Chrome Version 88.0.4324.96, (x86_64)

**What did you do? Please explain the steps you took before you encountered the problem.**
I have activated many animations (10-40). After all the animations were destroyed by me.

**What did you expect to happen?**
I wish there were no lottie objects in browser memory

**What actually happened? Please include as much _relevant_ detail as possible.**
In memory I saw a lottie objects.
<img width="951" alt="Снимок экрана 2021-01-22 в 12 24 42" src="https://user-images.githubusercontent.com/46839102/105472657-457f4b80-5cad-11eb-9697-deaad01b7101.png">
<img width="953" alt="Снимок экрана 2021-01-22 в 12 26 26" src="https://user-images.githubusercontent.com/46839102/105472662-46b07880-5cad-11eb-8411-ba22e874290d.png">
<img width="951" alt="Снимок экрана 2021-01-22 в 12 26 49" src="https://user-images.githubusercontent.com/46839102/105472665-47490f00-5cad-11eb-8e35-6f1d9d07ac84.png">
<img width="952" alt="Снимок экрана 2021-01-22 в 12 27 02" src="https://user-images.githubusercontent.com/46839102/105472666-47490f00-5cad-11eb-825c-7d9cff350d3e.png">
<img width="951" alt="Снимок экрана 2021-01-22 в 12 27 13" src="https://user-images.githubusercontent.com/46839102/105472669-47e1a580-5cad-11eb-9934-a2cf1dca3dbc.png">

**Comment by bodymovin** [comment]
those objects you're seeing belong to the lottie library, not to the animation instances themselves.
There's also some object pooling that get cached for reuse between frames and animations that don't get cleared. But that is limited in space and it should not be that large.
Is there a particular issue you're seeing because of this?
You can always clear everything by clearing the lottie library from the global scope by doing `window.lottie = null` and `window.bodymovin = null`
