### ISSUE TITLE
Lottie animation not working

### ISSUE THREAD

**Issue by hreverman** [airbnb/lottie-web#2458]
Hi, new to making lottie animations & having some issues when I export the animation. I'm using masks & stokes in my animation - its a logo reveal, handwritten kind of animation. When I export it, it doesn't look like my animation at all. It also doesn't time correctly when played. Am I doing something that isn't supported? attached below are screenshots of what the logo should look like when revealed vs what it looks like in lottie

Here's a link to the after effects file. if you look at it, ignore the loading style animation in there.
https://drive.google.com/drive/folders/1XGgknIEJR9kXdS1SYQebVqZYg-Omgc7b?usp=sharing

![Screen Shot 2021-02-05 at 3 38 41 PM](https://user-images.githubusercontent.com/78620096/107086720-645f0100-67c8-11eb-8fe6-10f9c535a07b.png)
![Screen Shot 2021-02-05 at 3 38 51 PM](https://user-images.githubusercontent.com/78620096/107086724-64f79780-67c8-11eb-9896-8548a38dbe76.png)

**Comment by bodymovin** [comment]
Hi, it looks like the images are missing from that animation. That's why you see those colors.
Also, the stroke effect is partially supported, so that's probably why it doesn't look the same.
Unfortunately, for this type of animation with effects and video layers, I don't think lottie will be of much help.

**Comment by kudanai** [comment]
Hope this issue is resolved. I'm closing this one for now. Please re-open if still relevant
