### ISSUE TITLE
Poor performance in Safari

### ISSUE THREAD

**Issue by artola** [airbnb/lottie-web#2498]
Playing several animations have good performance in Chrome while in Safari it is too sluggish.

**Tell us about your environment**
Reproduced in many computers.

* **Browser and Browser Version:**
Safari v14.1

* **After Effects Version:**
Unknown

**What did you do? Please explain the steps you took before you encountered the problem.**
I can confirm that the animation consumes a huge quantity of memory, near to 1 GB.

**What did you expect to happen?**
It should play smooth.

**What actually happened? Please include as much _relevant_ detail as possible.**
Playing animations in Chrome are OK, but in Safari is very sluggish and consume too much memory, making the computer irresponsive.

**Please provide a download link to the After Effects file that demonstrates the problem.**
I have created a Codesanbox [source](https://codesandbox.io/s/lottie-p1p4d?file=/src/App.js) running just 1 animation, here visible the [outcome](https://p1p4d.csb.app/), for example open it in Chrome and compare with Safari.
Available here the [Animation](https://codesandbox.io/s/lottie-p1p4d?file=/public/rocket.json).

**Comment by bodymovin** [comment]
I see that the animation is using 7 square inverted masks of 1920 x 1080px
I'm not sure what is producing them since I don't have the .aep, but if you can remove them which looks possible, the animation should run much more smoothly.
Safari has very poor performance with svg masks in general and specially large masks.
Regarding memory itself, I don't see the same profile when testing it, but I don't think that's related to the issue.

**Comment by artola** [comment]
@bodymovin Thanks a lot for the prompt reply. I have required the ".aep" file to better understand what causes the poor rendering. It must be something in this kind of animation, because we have others more animated without problems.

**Comment by artola** [comment]
Here a link to download the AEP file containing the above mentioned animation (among others) with sluggish rendering only in Safari: https://p1p4d.csb.app/animations.aep.zip

@bodymovin I will appreciate any hint about why this happen and mainly how to avoid it.

**Comment by bodymovin** [comment]
Alpha inverted masks require to create a full mask the size of the composition in order to invert the effect of an alpha mask. 
But if you use a regular alpha mask it should already work much better.
So for example in layer `Linie 1.2 Konturen` you can change the invert alpha to an alpha mask and the revert the trim path to go from end 0 to end 100%.
Another option is to precomp those layers and make sure the precomp is as small as the content so the inverted masks don't take all the main comp size.

**Comment by artola** [comment]
@bodymovin 👌 Thanks a lot, I will forward to the designer. (Gracias Hernan)

**Comment by artola** [comment]
Thanks again @bodymovin ... your hint did the difference for our case, now the animation runs so smooth in Safari as in Chrome. 👏
