### ISSUE TITLE
Add support for sound events

### ISSUE THREAD

**Issue by MKGitHub** [airbnb/lottie-web#261]
I.e. when a sound is played in AE make it an event/callback with an ID to identify the sound so that it can be played later in code. Whichever language the code is written in.

**Comment by bodymovin** [comment]
I've been exploring supporting sound, but it's not an easy task.
You can always use eventlisteners on the animation and play them.

**Comment by mmp7700** [comment]
After effects isn't great for sound either. But this would be an awesome feature. I think your suggestion to add eventListeners is the best way to go. The creative ways you could use this plugin/api are incredible.

**Comment by PerfectedTech** [comment]
@bodymovin would outside help be something of interest to get this feature integrated?

**Comment by samcreate** [comment]
What about just exporting after effects markers as event markers we could tie into?

**Comment by kudanai** [comment]
Hey there. It's been a while since this issue was raised. There are now a few resources you can refer to

[https://github.com/airbnb/lottie-web/wiki/Audio](https://github.com/airbnb/lottie-web/wiki/Audio)
[https://lottiefiles.github.io/lottie-docs/advanced_interactions/#level-8-sound-effects](https://lottiefiles.github.io/lottie-docs/advanced_interactions/#level-8-sound-effects)

Hope that's helpful.

I'm closing this issue for now. Please feel free to re-open
