### ISSUE TITLE
Missing Documentation for `tt`- Require advice for Adobe XD

### ISSUE THREAD

**Issue by C4Framework** [airbnb/lottie-web#2669]
The team at AdobeXD have recently implemented a feature for adding Lottie files to a prototype file. Currently, Lottie files exported from [Flow]() do not work in the XD environment. 

**Tell us about your environment**
MacOS

* **Browser and Browser Version:**
* Chrome 95

* **After Effects Version:** N/A
* **Flow Version:** 1.12.1

**What did you do? Please explain the steps you took before you encountered the problem.**

XD have offered a potential solution: https://helpx.adobe.com/xd/kb/known-issues.html

They suggest replacing the variable **"tt"** with **"xx"**... however, this approach is breaking.

Our understanding is that the **"tt"** variable denotes whether or not a group will mask to its bounds.

Here is an image of a group in Flow... the green layer is clipped by the group whose masks to bounds property is toggled **on**:

![groupWithMasking](https://user-images.githubusercontent.com/1447498/139135084-04f8cda9-0633-479e-b5a3-a3a525fa3daf.png)

After exporting this file to Lottie Web, we see an accurate representation:

![unmodifiedExport](https://user-images.githubusercontent.com/1447498/139135245-b0ffa70c-dfdd-4e26-8e77-846a579f0d0e.png)

After making the XD team's suggested change we see this:

![modifiedChange](https://user-images.githubusercontent.com/1447498/139135321-374bd68e-289e-4620-8cd0-624c58121ec8.png)

**What did you expect to happen?**
I actually expected their solution to **not** work. 

**What actually happened? Please include as much _relevant_ detail as possible.**
The solution provided by XD didn't work as expected. 

**HELP REQUEST**
The bodymovin-extension repo has a function that exports the value of **"tt"** like so:

```
function(e, t, n) {
    "use strict";
    n(17)("fixed", function(e) {
        return function() {
            return e(this, "tt", "", "")
        }
    })
}
```

However, this variable is not documented in either the bodymovin or the lottie-web repos. **Could we please add the documentation for this variable?**

I would like to be able to respond to the XD team with an accurate description of the variable to help find a solution so that the Lottie project has more reach.

**Comment by bodymovin** [comment]
After looking into the json I've found why it doesn't work correctly. Lottie doesn't accept the "tt" property with value "0", and it breaks when parsed.
So the search and replace that should be done to prevent the file from breaking is every occurrence of `"tt":  0.0` for `"xx": 0.0`
Apart from that, for layers that are masked, the property "tt" should be set on the masked layer, and a property "td" should be set on the masking one.
The file exported from Flow is not including the "td" prop and that's why the mask is not working correctly.
So the issue does not seem related to Adobe XD, but to Flow
Here is a specification with the information
https://github.com/lottie-animation-community/docs/blob/matte_masks_specs/Lottie_Specification.md#matte-masks

**Comment by C4Framework** [comment]
Amazing thanks. We'll work this into our next release.

**Comment by C4Framework** [comment]
Thanks for the help @bodymovin, really appreciate it. 

Question... why would our files previously have worked on the Lottiefiles site (and in our own exports) but not in XD? Would it be that XD wrote or modified their own player?

**Comment by bodymovin** [comment]
I'm not completely sure, but they're probably using the skottie player, isntead of the lottie web player, which might not be as flexible when getting unsupported values.

**Comment by C4Framework** [comment]
That makes sense. Thanks again.
