### ISSUE TITLE
random() doesn't feel very random in expressions

### ISSUE THREAD

**Issue by mbasaglia** [airbnb/lottie-web#2672]
I was experimenting with expressions and noticed that calling `random()` always returns the same value in the same expression.

The value only changes when the animation is loaded.

I think the issue is that the seed is initialized every time the expression is evaluated: https://github.com/airbnb/lottie-web/blob/bb71072a26e03f1ca993da60915860f39aae890b/player/js/utils/expressions/ExpressionManager.js#L659-L661

Not sure if this is intentional or not, but it does feel a bit odd

Attached an example animation (zipped so I could attach it)
[random.json.gz](https://github.com/airbnb/lottie-web/files/7454701/random.json.gz)

**Comment by bodymovin** [comment]
Hi, the seed is set only once, but the random is seeded on each evaluation since multiple expressions could try to seed the random method on their own overwriting the previous seed.
Perhaps I could declare a random method in the scope of each expression, but I have to check if that would work.
Another thing is that, if I remember correctly, the seed has to be deterministic per frame.
Anyway, this is a workaround to try to emulate AE as much as possible, but I would advice not using random if possible, since it has a significant overhead in terms of processing the expression.

**Comment by mbasaglia** [comment]
currently random() returns the same value on every frame, it only changes when the animation is reloaded

**Comment by bodymovin** [comment]
fixed. For some reason the time component of the seed got lost on some mere.

**Comment by kudanai** [comment]
@mbasaglia is this issue still present?

**Comment by mbasaglia** [comment]
seems fine
