### ISSUE TITLE
playSegment and currentFrame issue

### ISSUE THREAD

**Issue by kartik2014** [airbnb/lottie-web#2845]
I have 4 frames in my animation json - 0, 120, 240, 360 and then I have below code to playsegment :
![image](https://user-images.githubusercontent.com/6239284/187918512-7676ab11-7798-4aa4-9231-a21d3750ce8b.png)

It works fine 0 to 120 and 120 to 240,  but after it reaches 240, I am getting currentFrame = 120, so in the next cycle it goes from 120 to 360 rather than 240 to 360. Not sure why currentFrame returns 120 although it should be returning 240 after 120 to 240 cycle finishes.

Also, how can i progressively reverse the animation back i.e 360  - 240 -120 - 0

```
lottieConfig = {
        path: 'json file path',
        renderer: 'svg',
        autoplay: false,
        loop: false
    };
```

**Comment by bodymovin** [comment]
hi, currentFrame is relative to the duration of the current segment, not to the absolute value defined in After Effects. You might want to use also `firstFrame` if you need the absolute value

**Comment by kartik2014** [comment]
@bodymovin  looks like `currentRawFrame + FirstFrame` return the correct result. Please let me know if this is correct ?

**Comment by bodymovin** [comment]
yes, that should be rigth

**Comment by kartik2014** [comment]
thanks @bodymovin !

**Comment by simeyla** [comment]
@bodymovin Would you be able to make this behavior clearer in the documentation. I was INSANELY confused by this and had to step through all the code to figure it out. It's very unintuitive that `currentFrame` means the absolute frame one minute and then gets reset to 0 when playing a segment. I am synching things based on the frame number and so everything broke in a very confusing way. So I spent some time trying to fix my own code when it wasn't the problem.

The fix is simple (`currentFrame + firstFrame`) but it's very confusing and frustrating until you figure it out! And then I'm not even sure what happens during a segment if I run `goToAndStop(frame)`.

I was going to suggest adding a comment about this to the [`playSegments`](https://github.com/airbnb/lottie-web#playsegmentssegments-forceflag) section but then I noticed there isn't even a `currentFrame` section!
