### ISSUE TITLE
Lottie in Ceros 

### ISSUE THREAD

**Issue by straycloud** [airbnb/lottie-web#2959]
I'm hoping someone can help. I'm trying to pin point the cause of an error when using Lottie_html on a platform called Ceros. It actually works fine until want to rig with a plugin called Limber. Outside of Ceros and in their preview environment it works just fine (never had an issue actually). But in production or when exported as a standalone site and run locally it fails at a certain point (just with animations with Limber in them). 

I've added console log calls to try and pin down the issue and this is where I think it is happening: 
<img width="1242" alt="lottie-issue" src="https://user-images.githubusercontent.com/45208671/230131950-8e41d547-25de-49e4-9315-ae983742d117.png">

It looks something is causing the elements to not get created correctly. the 'undefined" (and maybe the "true") is what is causing the error. Can someone point me to where I can see where/what values are being assigned to the elements array? Just trying to get the bottom of this rabbit hole. 

Thanks.

**Comment by bodymovin** [comment]
hi, can you share a reduced example of the animation that is failing?

**Comment by straycloud** [comment]
Happy to. the attached is just a basic Limber limb (for the sake of finding the issue), no animation even done to it. When I test this with just Lottie web I have no issues. when it test this in a Cero's preview environment I have no issue. When I test it in production it gives me that result. I can replicate the production environment since they allow a standalone export. Co I can probably supply that as well. My best guess is there is some conflicting variable that maybe overriding the build function in Lottie. 
[limbnoMoveGuidesOn.js.zip](https://github.com/airbnb/lottie-web/files/11186322/limbnoMoveGuidesOn.js.zip)

**Comment by bodymovin** [comment]
If it is related to expressions, in general it's because the build process is removing "unused" code from the library.  
But in this case, it's not really unused code, since expressions are relying on a declared function that has been removed.  
Yes, a running environment where this is failing could be helpful.

**Comment by straycloud** [comment]
[Lottie-Ceros-local.zip](https://github.com/airbnb/lottie-web/files/11186472/Lottie-Ceros-local.zip)

I zipped it up. there are two gray buttons. left one loads the limber one, right one loads a non limber animation. The non limber one will work fine, the limber one won't. 

Thanks thanks. if you have point me to what could be the cause I can address it on a case by case basis.

**Comment by bodymovin** [comment]
expressions need access to the `eval` function in order to work. It seems there is a feature flag configuration declared in the index.html, on the `window.cerosContext` that removes the eval function.  
"Remove window.eval":true  
In order to support these animation you'd need change that flag.   
Keep in mind that `eval` can be dangerous if it is misused, so you need to make sure that this doesn't open any vulnerability on your site.

**Comment by straycloud** [comment]
Amazing. Thanks I'm going to contact the support team and see what can be done!
