### ISSUE TITLE
Adventure Time Parallax effect

### ISSUE THREAD

**Issue by azun1te** [airbnb/lottie-web#576]
Hello I've been trying to recreate the parallax effect as seen here: https://codepen.io/airnan/pen/NjayEE using simple shapes. 

Everything seems to be working fine: mouse position/distance registering and calculating correctly, but for some reason the **camera is not registering**.

I think it has something to do with the fact that my camera object has been rendered differently and is missing some information:
http://imgur.com/Obc0JFJ
therefore i cannot set these parameters correctly:
http://imgur.com/Lzc5e4u

Can you please check out what I am missing?
I've included .zip with AE project and code.
http://www117.zippyshare.com/v/idpnn5rI/file.html

**Comment by azun1te** [comment]
Still haven't found the answer. All it would take is the people who worked on that Adventure Time project to share the camera layer specifications or even share the project in a prive message and I could close this issue.

**Comment by azun1te** [comment]
So I made it work by replacing my json camera object code with the raw camera object code of original project's json file, but I understand that's really not a propper way to do it :D.

Still, if someone knows why my camera layer is rendering differently I would be really grateful.

**Comment by bodymovin** [comment]
Hi, can you share your file via WeTransfer?

**Comment by Shirkit** [comment]
Hi,

I'm having the exact same issue. I'm trying without animations and a default camera. Animating the camera or not, the end result is the same. I can't seem to get the camera working, just as @azun1te described.

I tried exporting as many times and I had an idea, and finally had the idea to copy and paste the camera settings from the JSON from Adventure Time, and it works.

I think that by having the original AEP file I could better understand why my project is failing.

I have done exactly the same as the OP did, from the original editing, to copying the camera. But I'd love to know exactly why, and I think the original AEP would solve that.

My file is here: https://www.atlantidastudios.com/peu.aep

**Comment by bodymovin** [comment]
Nice! So you've figured out how to make it work?

**Comment by Shirkit** [comment]
After seeing the original After file I understood how to make it work.

As @azun1te mentioned, the issue is that the camera object, when we export from AE it does not contain the data structure required to make the desired 3D effect IF the camera has no animation.

If the camera has an animation, it doesn't allow for it to be changed programmatically it's the angle and position, because the camera's animation override any change we make on it's position.

The only way I came up with it working was to allow the camera has to animate a **VERY SMALL amount between TWO REALLY DISTANT frames**. After you setup the camera like that, you can change the camera's ks.p.k.s and ks.p.k.e 

Also the camera has to animate from the very first frame to the very last frame.

With those things in mind, when you export the AE project, you'll be able to change the camera's position programmatically.

**Comment by Numeo** [comment]
Hi ! Thank you @bodymovin for your work and this **fantastic tool**. 
I'm trying to reproduce the parallax effect in your aventure time animation. After a lot of try to modify AE properties without destroy and reload animation, I found the solution with this interesting post. It functions now when I modify two keyframes with a small amount between them, but I wonder if it would be possible to access AE properties without add keyframes. Are there technical issues that make that complicated ?

**Comment by bodymovin** [comment]
@Numeo Any property that doesn't have keyframes is calculated only once in order to improve performance by skipping unnecessary checks.
That's why this workaround is needed to update values.
