### ISSUE TITLE
Covert to Outline shape distorted in demo preview

### ISSUE THREAD

**Issue by jennifer-shen** [airbnb/lottie-web#591]
* **Browser and Browser Version:10.1.2 **
* **After Effects Version: 14.0.1.57 **

Hey guys,

I'm having a bit of problems with exporting my AE animations using bodymovin. I imported my .ai file and converted the .svg images to outlines. After converting to outlines, the shapes on my demo preview becomes super distorted. I've tried importing another .ai file with the same shapes, and creating a new layer for the shapes on AE, but it doesn't seem to solve the problem. The previous animations I've exported had no problems at all! It's just this one. Please help :(. 

Preview on AE
<img width="328" alt="screen shot 2017-08-17 at 5 35 08 pm" src="https://user-images.githubusercontent.com/30355080/29434822-8e055d08-8372-11e7-8a1e-556797e717ca.png">
After exporting from bodymovin on demo
<img width="618" alt="screen shot 2017-08-17 at 5 35 42 pm" src="https://user-images.githubusercontent.com/30355080/29434825-91b9de38-8372-11e7-9f03-c33b46f33f01.png">

**Comment by bodymovin** [comment]
Hi, once you convert your .ai layers to .ae shapes, unfortunately, AE adds an unnecessary extra square path merged with the actual shape with a Merge Path. Since bodymovin doesn't support merge paths, you need to delete those square paths and the merge path property.
I'm guessing that's why you see it like that.
There is an AE script that does that automatically.
http://aescripts.com/explode-shape-layers/
