### ISSUE TITLE
Bodymovin Blurry Output and some other problems

### ISSUE THREAD

**Issue by jorjani1** [airbnb/lottie-web#694]
[Jorjani1.zip](https://github.com/bodymovin/bodymovin/files/1414816/Jorjani1.zip)

**Tell` us about your environment**

* **Browser and Browser Version:**
Google Chrome Version 61.0.3163.100
* **After Effects Version:**
AfterEffects CC 2017 14.2.1.34
**What did you do? Please explain the steps you took before you encountered the problem.**
i built this in AE and Render
**What did you expect to happen?**
!--mentioned below
**What actually happened? Please include as much _relevant_ detail as possible.**
now i have problem : 
the exported demo file in the browser and the preview animation in bodymovin extension blured !!!
like low quality pixel file . but i used 3 .ai files created in illustrator

**Please provide a download link to the After Effects file that demonstrates the problem.**
[Jorjani1.zip](https://github.com/bodymovin/bodymovin/files/1414818/Jorjani1.zip)

as you can see its work with gif but blurry in svg !
![image](https://user-images.githubusercontent.com/24686293/32004280-3e29b136-b9ae-11e7-89ca-8f8fe633084c.gif)

**Comment by bodymovin** [comment]
Hi, there seems to be an issue with the size of the logos, but I can't figure out what yet.
Are they different between them?

**Comment by jorjani1** [comment]
Their was different in resolution !! but i changed the .ai files resolution to 1000×1000 in illustrator .I dont really know what is the real difference between different resolution in vectors !
I mean why should vectors have resolution ?
They are all vectors ai files
I attached them below
[Logos.zip](https://github.com/bodymovin/bodymovin/files/1443150/Logos.zip)

**Comment by wonderment** [comment]
@jorjani1 The resolution shouldn't matter in general. Perhaps the width/height and x/y placement in AI shouldn't be decimal pixels? E.g. 500.62px to 500px.

Maybe the interpretation by all of the SVG transforms as output by Bodymovin is cause for blurriness because of pixel boundaries. If so, it might be a browser rendering problem similar to various pixel splitting between Firefox, Chrome, etc.

**Comment by bodymovin** [comment]
It's probably related to the html renderer and how browsers manage 3d transformations.
Since 3d transforms are done in the compositing phase, layers are already painted and they don't get an appropiate repaint to adjust to the new size.
But I don't know in this specific case why 2 of them get pixelated and the other one doesn't

**Comment by wonderment** [comment]
It seems based on that, using 3D layers in AE isn't practical at this point (unless the responsive output isn't a concern/consideration).
