### ISSUE TITLE
Combining several bodymovin animations bogs down browser/plays very slowly on mobile devices

### ISSUE THREAD

**Issue by jvolvovski** [airbnb/lottie-web#705]
Hi,
I am attempting to combine several bodymovin animations on the homepage of a website.
You can see it here:
http://theadventureschool.com/new-site/

It plays ok on a desktop browser for a bit, and then my laptop fan starts to run.
On iPad/iPhone devices it really chugs and plays 1/10th the speed.

I am wondering if there is anything can be done to improve performance (how I'm calling the json files, etc.) or if this is just the nature of combining several complex animations.

Any help would be appreciated.

Thanks,
Jenny

**Comment by bodymovin** [comment]
Hi, it's probably a combination some things:
- don't animate the left property of the cloud elements. That triggers a new layout every time that is an expensive task. Try using transform instead.
- clouds are getting clipped with masks instead of clip paths and I'm guessing it's because you're using strokes as masks. That is very expensive as well.
- bird wings are also being masked instead of clipped. Is there another way you can reproduce that animation?

**Comment by jvolvovski** [comment]
Thanks, will definitely do all those suggestions.
Even if I comment out all those elements (the birds & clouds), it still plays very slowly on the phone. Is it because the .json files for the other 3 elements are around 200kb? Is there anything that can be done to optimize the .json files after they've been exported?

Thanks again,
Jenny

**Comment by bodymovin** [comment]
no, the filesize of the json shouldn't affect at all.
I don't see anything too expensive on the other animation, but I might be missing something.
Are you using rubberhose?

**Comment by jvolvovski** [comment]
Yep, using rubberhose.

**Comment by wonderment** [comment]
@jvolvovski Just a heads up: outside of the animation drag, on Android, there's fractal/odd rendering on the dog and person on the left, so you may have more issues at hand outside of Bodymovin.
