### ISSUE TITLE
Is there a tool for viewing docs/json?

### ISSUE THREAD

**Issue by minimalviking** [airbnb/lottie-web#742]
I'm trying to understand bodymovin json format and I've noticed that docs/json seem to be in a format suitable for viewing in some kind of json documentation tool, but I wasn't able to find any mention of that anywhere

**Comment by bodymovin** [comment]
I haven't found any suitable tool for now. And I think the documentation format is not respecting all the requirements.
If anyone can help on this, in would be great.

**Comment by DaanDirk** [comment]
When you view a json in firefox you can open and close brackets with a click.
Or do you mean something like this:
https://transform.now.sh/js-object-to-json/

**Comment by felippenardi** [comment]
@bodymovin Is there a way from After Effects to get the path to a specific property?

**Comment by felippenardi** [comment]
I'm finding it difficult to understand the json output referencing the docs without a preview tool. Do you have a better workflow?

**Comment by mundane140** [comment]
Please don't take this the wrong way, I am new to this. I am having a hard time grasping the issue itself. What are we trying to do here?  What are we looking for?

**Comment by felippenardi** [comment]
I don't understand your question. Are you having some problem or just trying to get in the thread?

**Comment by mundane140** [comment]
I am just trying to understand the issue. It says "is there a tool for viewing docs/json". 
What kind of view is being referenced to here?

**Comment by felippenardi** [comment]
Sure! Let me give you some context. The output of converting an After Effects animation into lottie is a json file. This JSON file is filled with two-letter properties describes the vector and the animation.

If you modify the right properties in this JSON, you can modify an animation at runtime—which is very powerful. But parsing this JSON is difficult because it contains one to two letter properties. You have `o` instead of `opacity`, and so on so forth.

What we are asking here is a tool to visualize this JSON in a way we can understand what the properties are. That is what we mean with "a tool for viewing docs/json`.

**Comment by mundane140** [comment]
Alright, I'll do some research and get back in a day or two.

**Comment by mundane140** [comment]
Have you tried viewing a JSON Schema on code beautify?
https://codebeautify.org/jsonviewer/

It generates an organised view from a JSON schema.

**Comment by guiccbr** [comment]
@minimalviking , I tried to use `@adobe/jsonschema2md` to auto-generate the markdown documentation for the json schemas, and had partial success. Some of the json schemas fail during the validation step, so I had to ignore those (maybe related #1167).

Parsing only the jsons inside the layers directory work, for instance:

`./node_modules/.bin/jsonschema2md -d docs/json/layers -o dist/docs -e json -v 04`
