### ISSUE TITLE
After Effects Export Frame Drop Issue

### ISSUE THREAD

**Issue by spence-lab** [airbnb/lottie-web#748]
Hello,

I have a simple animation that seems to loop smoothly when previewed in AfterEffects,
but seems to 'jump' when looping in the rendered file. 

It appears to be sort of frame drop or double up, but I can't seem to replicate it within the AfterEffects document or the Bodymovin pane Preview.

Is there a way for me to render a clean, loopable animation?

The correct final frame in AfterEffects

![screen shot 2017-12-03 at 4 19 15 pm](https://user-images.githubusercontent.com/34219784/33529973-56704ff0-d846-11e7-9d3a-e7f3b05f71ad.png)

The troublesome frame when rendering in Chrome

![screen shot 2017-12-03 at 4 21 39 pm 1](https://user-images.githubusercontent.com/34219784/33529974-567f14f4-d846-11e7-82d6-4bbaadc0c56c.png)

My AfterEffects file can be found here:
[SPENCELAB-Spinny_Globe.zip](https://github.com/airbnb/lottie-web/files/1525220/SPENCELAB-Spinny_Globe.zip)

Thank you!

**Comment by bodymovin** [comment]
Hi, the issue is because the player does subframe interpolation. Which means that it will render inbetween frames to get a smoother animation.
Since you have a layer with two consecutive keyframes (Shape Layer 13) on frame 0 and 1 applied to the mask, the mask will have unexpected intermediate positions.
You can do one of two things:
- convert those keyframes to Hold Keyframes in AE
- set animation.setSubframe(false) in the player. That way the player will not interpolate between frames.

**Comment by spence-lab** [comment]
Brilliant!
Thank you so much!
