### ISSUE TITLE
Paths are clipping on export

### ISSUE THREAD

**Issue by psql** [airbnb/lottie-web#872]
Hey again! 

Running: Latest after effects and bodymovin

**Issue**:
Getting some clipping around vector paths..

![image](https://user-images.githubusercontent.com/688842/36333841-3eea9cf0-1347-11e8-8394-9bda9433cdf6.png)

**output**: https://cl.ly/pbHn
supposed to look like this: https://cl.ly/pa9V

**Here's the after effects source**: https://cl.ly/pZoV
Using rubberhose rigs, but I've used the same version before with no issues.

**Comment by bodymovin** [comment]
Hi, I can't download the file because Chrome is blocking it.
But I've checked your project and I see that you have 3d layers.
3d layers only work with the html renderer, and the html renderer doesn't go well with strokes.
If you create a transparent rectangle shape larger than the strokes, it should render fine.
Or you can remove the 3d set from your layers.
