### ISSUE TITLE
Round Cap Stroke doesn't work

### ISSUE THREAD

**Issue by tomwilusz** [airbnb/lottie-web#899]
**Tell us about your environment**

* **Browser and Browser Version:** Safari Version 10.1.2
* **After Effects Version:** CC 2018

**What did you do? Please explain the steps you took before you encountered the problem.**
Just downloaded Bodymovin from AE scripts and created Envelope with rounded strokes. After that I choose the settings (https://drive.google.com/open?id=1coJ-9p6snuyW5tBCyq7uv2iEuqgMdsyX) and hit render.

**What did you expect to happen?**
To have Rounded Cap Stroke. Ive seen in many tutorials where everybody gets this rounded effect but me - don't.

+ the artwork is not responsive.

**What actually happened? Please include as much _relevant_ detail as possible.**
Check the screenshot: http://prntscr.com/ioz68h
**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/open?id=1coJ-9p6snuyW5tBCyq7uv2iEuqgMdsyX

Please help me with this issue.

**Comment by bodymovin** [comment]
Hi, 3d layers don't work well with stroke shapes.
But if you surround your strokes with a rectangle and a fill of any color with opacity at 0, they should look fine.
There is another issue probably because of combining 2d and 3d layers, I'd suggest that you try using only 2d animations if possible, or convert all to 3d.
