### ISSUE TITLE
Difference between lottie_light.js and lottie.js?

### ISSUE THREAD

**Issue by zhengs** [airbnb/lottie-web#929]
Could you explain the difference between lottie_light.js and lottie.js in terms of the features they support?

I suppose lottie_light_min.js and lottie_min.js are just minified versions of each, is that correct?

**Comment by bodymovin** [comment]
lottie_light has only the svg renderer and doesn't support expressions.
yes, the min files are minified versions.

**Comment by simeyla** [comment]
So will `lottie_light` blow up nicely if I try to open an unsupported file - or will things just look corrupted.

I get given `json` files by our animator and have no idea what he's using in them. Is there an easy way to tell?

**Comment by bodymovin** [comment]
@simeyla it should work fine but animations won't render correctly if they have expressions or effects.
There's no easy way right now to know if you should use the light version or the full version.

**Comment by honeyamin** [comment]
@bodymovin  hi, what is support expressions exactly? can i use lottie_light.min by interactivity?

**Comment by Ricardo0621** [comment]
> @bodymovin hi, what is support expressions exactly? can i use lottie_light.min by interactivity?

Hi @honeyamin, I'm using Bodymovin's lottie_light.js with scroll interactivity [here](https://ricardo0621.github.io/) and it works just fine for me :)

**Comment by honeyamin** [comment]
> > @bodymovin hi, what is support expressions exactly? can i use lottie_light.min by interactivity?
> 
> Hi @honeyamin, I'm using Bodymovin's lottie_light.js with scroll interactivity [here](https://ricardo0621.github.io/) and it works just fine for me :)

nice job bro

**Comment by jimlefevre** [comment]
Adding to this stack here. I'm currently making Lottie animations for a client who has to use Lottie Lite due to security issues (not 100% sure why but it's a site that deals with money so I can understand the concern).

Excluding the issue of expressions we are hitting snags of some animations 'sticking' in Lottie Lite that don't in the normal player. I wonder if anyone else has had these?

To be honest they are quite complicated animations with embedded comps so that might be the cause but I'm stripping out the AE composition and trying to figure out by trial and error the things that trigger the sticking.

Oh also we are experiencing a strange one-pixel flashing line on either side too. Grrrr.. It's such a glorious piece of software but frustrating I can't get these things to work.

**Comment by bodymovin** [comment]
@jimlefevre hi, can you share the .aep of the animation that's failing so I can check it?

**Comment by jimlefevre** [comment]
Hey @bodymovin,

Thanks for the offer, unfortunately I can't share as it's for a client with a Do Not Share attitude BUT...! Having spent days doing multiple tests of deleting various things and re-rendering I managed to stop it sticking - it felt like it was a series of embedded comps that had 'fill' effects in them which I brought up into one of the higher level comps (as it happened the 'fill' effect was unnecessary anyway as I could have just changed the stroke colour which I ended up doing manually).

But the single line pixel flashing was still there on both sides. 

Gah.

I tried loads of variations of solutions including adding blocks of colour of the top and none of them worked  HOWEVER....! Literally as I was about to give up I thought I'd try put that whole main composition in a new composition and hey presto.... when I rendered it the flashing lines had gone!!

Anyone with this issue I'd suggest the same and if I find the same problem with a shareable comp I'll send it over.

Thanks so much for the offer again though.

Jim
