### ISSUE TITLE
IE11 (maybe all IE) is resizing and not displaying my output correctly 

### ISSUE THREAD

**Issue by EddieE1** [airbnb/lottie-web#986]
Hi, my final output seems to fail hard on IE11. It resizes it very small and oddly 2 letters are missing from my output. Chrome it looks perfect. 

IE11 Screenshot here: 
![ie-screenshot](https://user-images.githubusercontent.com/8733453/39102124-55b0d80c-46e4-11e8-8850-a249396b7996.PNG)

Chrome Screenshot here:
<img width="701" alt="chrome-screenshot" src="https://user-images.githubusercontent.com/8733453/39102126-61b76012-46e4-11e8-93b8-5b311a8e6b8f.png">

The site where this is all viewable is here: https://collectivegraphics.com.au/

Any help with this would be great?

Thanks
Ben

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by EddieE1** [comment]
Please disregard this issue. I moved to a background video with CSS... 

Thanks

Ben

**Comment by warpcgd** [comment]
@bodymovin 
Hi , I encountered the same problem. How did I solve it?

**Comment by warpcgd** [comment]
@EddieE1 
I have solved it , You need to add a fixed width on lottie

**Comment by phuch** [comment]
@EddieE1 could you show a example ot pseudo code?

**Comment by adriandmitroca** [comment]
For all of those suffering for that issue. In general, Internet Explorer 11 has serious issues with scaling SVG, even most simple ones.

Solution for this is usually setting fixed width / heights with valid ratio so the SVGs aren't downscaled or upscaled.

Of course, in real life this usually isn't an option, especially in terms of scaling and so on - that's why I've drafted small helper function, that takes care of adjusting missing size attributes on the fly so you don't have to worry about it.

https://gist.github.com/adriandmitroca/15de2e2ed3a5816a1cd5eb800a68b83b
