### ISSUE TITLE
Animation glitches in Safari and conflicting with css hover effects

### ISSUE THREAD

**Issue by v1z** [airbnb/lottie-web#997]
**Tell us about your environment**

* **Browser and Browser Version:**
Safari Version 11.1 (13605.1.33.1.2) (Mac OS)

* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**
I have some css hover effects on cards + lottie animations on it. Animations trigger on mouse enter and play reverse on mouse leave.

**What did you expect to happen?**
Smooth animations and correct hover effects

**What actually happened? Please include as much _relevant_ detail as possible.**
Animation glitches only in Safari and run well in other browsers. Also css hover effects (such as changing background-color) work wrong

**Please provide a download link to the After Effects file that demonstrates the problem.**
I don't have aep file, but can provide json with animation

Video preview of problem - http://s.csssr.ru/U3NRDBTBJ/20180428170708.mp4
JSON with one of the animation - https://drive.google.com/file/d/1bgL4xrMMOHQqkiqP4Vuaekqv4D5bfUa_/view?usp=sharing

**Comment by bodymovin** [comment]
Hi, can you share a link with the issue?
I can't identify the glitch in the video.

**Comment by v1z** [comment]
sure http://develop.siberian-pestovo.csssr.ru/tournament.html

**Comment by alexluong** [comment]
Did anybody fix this issue? I got the same kind of problem with Safari hover animation.

**Comment by alexluong** [comment]
@bodymovin Hi, thanks for commenting. After checking again with this repo, I realized I'm in the wrong place. I didn't use the library. I just got some problem with hover animation with Safari natively. Sorry.

**Comment by webdazign** [comment]
Hi, I can see this is closed, but I'm facing a similar issue with CSS animations while using the lottie animations. All other browsers work perfectly except for Safari. I have checked everywhere and had a few people look over it, but no one seems to see what the issue is and this is the only thread I've found with a similar issue.

Link: https://integrate.4points.com.au/sample/ 

If you click on the menu icon, and close and open and close etc, the menu bugs out and then becomes unresponsive completely.
